"""SMS delivery log message_type values must fit the database column."""

from app.services.sms.delivery_log import (
    MESSAGE_TYPE_EXAMINER_APPOINTMENT_LETTER_RELEASED,
    MESSAGE_TYPE_EXAMINER_INVITATION,
    MESSAGE_TYPE_EXAMINER_INVITATION_CUSTOM,
    MESSAGE_TYPE_EXAMINER_ROSTER_CUSTOM,
    MESSAGE_TYPE_INSPECTOR_CREDENTIALS,
    MESSAGE_TYPE_WORKFORCE_PORTAL_INVITE,
)

SMS_MESSAGE_TYPE_MAX_LEN = 64


def test_sms_message_type_constants_fit_column() -> None:
    for value in (
        MESSAGE_TYPE_INSPECTOR_CREDENTIALS,
        MESSAGE_TYPE_EXAMINER_INVITATION,
        MESSAGE_TYPE_EXAMINER_INVITATION_CUSTOM,
        MESSAGE_TYPE_EXAMINER_ROSTER_CUSTOM,
        MESSAGE_TYPE_EXAMINER_APPOINTMENT_LETTER_RELEASED,
        MESSAGE_TYPE_WORKFORCE_PORTAL_INVITE,
    ):
        assert len(value) <= SMS_MESSAGE_TYPE_MAX_LEN, value
