"""Modify subject and examiner models

Revision ID: 3cc69893e31e
Revises: a1b2c3d4e5f6
Create Date: 2026-01-28 17:06:16.495589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc69893e31e'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ELECTIVE', 'CORE', 'TECHNICAL_DRAWING_BUILDING_OPTION', 'TECHNICAL_DRAWING_MECHANICAL_OPTION', 'PRACTICAL', name='subjecttype').create(op.get_bind())
    op.add_column('examiner_applications', sa.Column('subject_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_examiner_applications_subject_id'), 'examiner_applications', ['subject_id'], unique=False)
    op.create_foreign_key(None, 'examiner_applications', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    op.add_column('subjects', sa.Column('type', sa.Enum('ELECTIVE', 'CORE', 'TECHNICAL_DRAWING_BUILDING_OPTION', 'TECHNICAL_DRAWING_MECHANICAL_OPTION', 'PRACTICAL', name='subjecttype'), nullable=True))
    op.create_index(op.f('ix_subjects_type'), 'subjects', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subjects_type'), table_name='subjects')
    op.drop_column('subjects', 'type')
    op.drop_constraint(None, 'examiner_applications', type_='foreignkey')
    op.drop_index(op.f('ix_examiner_applications_subject_id'), table_name='examiner_applications')
    op.drop_column('examiner_applications', 'subject_id')
    sa.Enum('ELECTIVE', 'CORE', 'TECHNICAL_DRAWING_BUILDING_OPTION', 'TECHNICAL_DRAWING_MECHANICAL_OPTION', 'PRACTICAL', name='subjecttype').drop(op.get_bind())
    # ### end Alembic commands ###
