"""Update qualification model

Revision ID: 11c4f5c70cb8
Revises: e32c8d92aa0e
Create Date: 2026-01-29 11:26:37.666523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11c4f5c70cb8'
down_revision: Union[str, None] = 'e32c8d92aa0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PhD', 'M.Ed', 'M.Sc', 'B.Ed', 'B.Sc', 'Bachelor', 'Diploma', 'Other', name='degreetype').create(op.get_bind())
    op.add_column('examiner_application_qualifications', sa.Column('degree_type', sa.Enum('PhD', 'M.Ed', 'M.Sc', 'B.Ed', 'B.Sc', 'Bachelor', 'Diploma', 'Other', name='degreetype'), nullable=False))
    op.add_column('examiner_application_qualifications', sa.Column('programme', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_examiner_application_qualifications_degree_type'), 'examiner_application_qualifications', ['degree_type'], unique=False)
    op.drop_column('examiner_application_qualifications', 'degree_diploma')
    op.add_column('examiner_qualifications', sa.Column('degree_type', sa.Enum('PhD', 'M.Ed', 'M.Sc', 'B.Ed', 'B.Sc', 'Bachelor', 'Diploma', 'Other', name='degreetype'), nullable=False))
    op.add_column('examiner_qualifications', sa.Column('programme', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_examiner_qualifications_degree_type'), 'examiner_qualifications', ['degree_type'], unique=False)
    op.drop_column('examiner_qualifications', 'degree_diploma')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examiner_qualifications', sa.Column('degree_diploma', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_examiner_qualifications_degree_type'), table_name='examiner_qualifications')
    op.drop_column('examiner_qualifications', 'programme')
    op.drop_column('examiner_qualifications', 'degree_type')
    op.add_column('examiner_application_qualifications', sa.Column('degree_diploma', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_examiner_application_qualifications_degree_type'), table_name='examiner_application_qualifications')
    op.drop_column('examiner_application_qualifications', 'programme')
    op.drop_column('examiner_application_qualifications', 'degree_type')
    sa.Enum('PhD', 'M.Ed', 'M.Sc', 'B.Ed', 'B.Sc', 'Bachelor', 'Diploma', 'Other', name='degreetype').drop(op.get_bind())
    # ### end Alembic commands ###
