"""Init models

Revision ID: 0f8b93803cec
Revises:
Create Date: 2026-01-26 19:36:47.684220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f8b93803cec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _create_enum_if_not_exists(name: str, values: tuple[str, ...]) -> None:
    """Create a PostgreSQL enum type only if it does not already exist."""
    vals = ", ".join("'" + v.replace("'", "''") + "'" for v in values)
    op.execute(
        f"""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = '{name}') THEN
                CREATE TYPE {name} AS ENUM ({vals});
            END IF;
        END
        $$;
        """
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _create_enum_if_not_exists("examinersubjectpreferencetype", ("ELECTIVE", "CORE", "TECHNICAL_DRAWING_BUILDING", "TECHNICAL_DRAWING_MECHANICAL", "PRACTICAL_COMPONENT", "ACCESS_COURSE"))
    _create_enum_if_not_exists("paymentstatus", ("PENDING", "SUCCESS", "FAILED", "CANCELLED"))
    _create_enum_if_not_exists("examinerapplicationstatus", ("DRAFT", "SUBMITTED", "UNDER_REVIEW", "ACCEPTED", "REJECTED"))
    _create_enum_if_not_exists("acceptancestatus", ("PENDING", "ACCEPTED", "DECLINED", "EXPIRED"))
    _create_enum_if_not_exists("allocationstatus", ("APPROVED", "WAITLISTED", "REJECTED"))
    _create_enum_if_not_exists("quotatype", ("REGION", "GENDER"))
    _create_enum_if_not_exists("markingcyclestatus", ("DRAFT", "OPEN", "ALLOCATED", "CLOSED"))
    _create_enum_if_not_exists("examinerdocumenttype", ("PHOTOGRAPH", "CERTIFICATE", "TRANSCRIPT"))
    _create_enum_if_not_exists("examinerstatus", ("ACTIVE", "INACTIVE", "SUSPENDED"))
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=True)
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('examiners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('office_address', sa.Text(), nullable=True),
    sa.Column('residential_address', sa.Text(), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('telephone_office', sa.String(length=50), nullable=True),
    sa.Column('telephone_cell', sa.String(length=50), nullable=True),
    sa.Column('present_school_institution', sa.String(length=255), nullable=True),
    sa.Column('present_rank_position', sa.String(length=255), nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', name='examinerstatus', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examiners_id'), 'examiners', ['id'], unique=False)
    op.create_index(op.f('ix_examiners_status'), 'examiners', ['status'], unique=False)
    op.create_index(op.f('ix_examiners_user_id'), 'examiners', ['user_id'], unique=True)
    op.create_table('marking_cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('total_required', sa.Integer(), nullable=False),
    sa.Column('experience_ratio', sa.Float(), nullable=False),
    sa.Column('acceptance_deadline', sa.DateTime(), nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'OPEN', 'ALLOCATED', 'CLOSED', name='markingcyclestatus', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'subject_id', name='uq_marking_cycle_year_subject')
    )
    op.create_index(op.f('ix_marking_cycles_id'), 'marking_cycles', ['id'], unique=False)
    op.create_index(op.f('ix_marking_cycles_status'), 'marking_cycles', ['status'], unique=False)
    op.create_index(op.f('ix_marking_cycles_subject_id'), 'marking_cycles', ['subject_id'], unique=False)
    op.create_index(op.f('ix_marking_cycles_year'), 'marking_cycles', ['year'], unique=False)
    op.create_table('examiner_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('examiner_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('allocation_status', postgresql.ENUM('APPROVED', 'WAITLISTED', 'REJECTED', name='allocationstatus', create_type=False), nullable=False),
    sa.Column('allocated_at', sa.DateTime(), nullable=False),
    sa.Column('allocated_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['allocated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cycle_id'], ['marking_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['examiner_id'], ['examiners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('examiner_id', 'cycle_id', 'subject_id', name='uq_examiner_allocation')
    )
    op.create_index(op.f('ix_examiner_allocations_allocated_by_user_id'), 'examiner_allocations', ['allocated_by_user_id'], unique=False)
    op.create_index(op.f('ix_examiner_allocations_allocation_status'), 'examiner_allocations', ['allocation_status'], unique=False)
    op.create_index(op.f('ix_examiner_allocations_cycle_id'), 'examiner_allocations', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_examiner_allocations_examiner_id'), 'examiner_allocations', ['examiner_id'], unique=False)
    op.create_index(op.f('ix_examiner_allocations_id'), 'examiner_allocations', ['id'], unique=False)
    op.create_index(op.f('ix_examiner_allocations_subject_id'), 'examiner_allocations', ['subject_id'], unique=False)
    op.create_table('examiner_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('examiner_id', sa.UUID(), nullable=False),
    sa.Column('application_number', sa.String(length=50), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', name='examinerapplicationstatus', create_type=False), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('office_address', sa.Text(), nullable=True),
    sa.Column('residential_address', sa.Text(), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('telephone_office', sa.String(length=50), nullable=True),
    sa.Column('telephone_cell', sa.String(length=50), nullable=True),
    sa.Column('present_school_institution', sa.String(length=255), nullable=True),
    sa.Column('present_rank_position', sa.String(length=255), nullable=True),
    sa.Column('subject_area', sa.Text(), nullable=True),
    sa.Column('additional_information', sa.Text(), nullable=True),
    sa.Column('ceased_examining_explanation', sa.Text(), nullable=True),
    sa.Column('payment_status', postgresql.ENUM('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', name='paymentstatus', create_type=False), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['examiner_id'], ['examiners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examiner_applications_application_number'), 'examiner_applications', ['application_number'], unique=True)
    op.create_index(op.f('ix_examiner_applications_created_at'), 'examiner_applications', ['created_at'], unique=False)
    op.create_index(op.f('ix_examiner_applications_examiner_id'), 'examiner_applications', ['examiner_id'], unique=False)
    op.create_index(op.f('ix_examiner_applications_id'), 'examiner_applications', ['id'], unique=False)
    op.create_index(op.f('ix_examiner_applications_payment_status'), 'examiner_applications', ['payment_status'], unique=False)
    op.create_index(op.f('ix_examiner_applications_status'), 'examiner_applications', ['status'], unique=False)
    op.create_index(op.f('ix_examiner_applications_submitted_at'), 'examiner_applications', ['submitted_at'], unique=False)
    op.create_table('examiner_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('examiner_id', sa.UUID(), nullable=False),
    sa.Column('document_type', postgresql.ENUM('PHOTOGRAPH', 'CERTIFICATE', 'TRANSCRIPT', name='examinerdocumenttype', create_type=False), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['examiner_id'], ['examiners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examiner_documents_document_type'), 'examiner_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_examiner_documents_examiner_id'), 'examiner_documents', ['examiner_id'], unique=False)
    op.create_index(op.f('ix_examiner_documents_id'), 'examiner_documents', ['id'], unique=False)
    op.create_table('examiner_examining_experiences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('examiner_id', sa.UUID(), nullable=False),
    sa.Column('examination_body', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('level', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['examiner_id'], ['examiners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examiner_examining_experiences_examiner_id'), 'examiner_examining_experiences', ['examiner_id'], unique=False)
    op.create_index(op.f('ix_examiner_examining_experiences_id'), 'examiner_examining_experiences', ['id'], unique=False)
    op.create_table('examiner_qualifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('examiner_id', sa.UUID(), nullable=False),
    sa.Column('university_college', sa.String(length=255), nullable=False),
    sa.Column('degree_diploma', sa.String(length=255), nullable=False),
    sa.Column('class_of_degree', sa.String(length=100), nullable=True),
    sa.Column('major_subjects', sa.Text(), nullable=True),
    sa.Column('date_of_award', sa.Date(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['examiner_id'], ['examiners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examiner_qualifications_examiner_id'), 'examiner_qualifications', ['examiner_id'], unique=False)
    op.create_index(op.f('ix_examiner_qualifications_id'), 'examiner_qualifications', ['id'], unique=False)
    op.create_table('examiner_subject_eligibility',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('examiner_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['examiner_id'], ['examiners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('examiner_id', 'subject_id', name='uq_examiner_subject_eligibility')
    )
    op.create_index(op.f('ix_examiner_subject_eligibility_eligible'), 'examiner_subject_eligibility', ['eligible'], unique=False)
    op.create_index(op.f('ix_examiner_subject_eligibility_examiner_id'), 'examiner_subject_eligibility', ['examiner_id'], unique=False)
    op.create_index(op.f('ix_examiner_subject_eligibility_id'), 'examiner_subject_eligibility', ['id'], unique=False)
    op.create_index(op.f('ix_examiner_subject_eligibility_subject_id'), 'examiner_subject_eligibility', ['subject_id'], unique=False)
    op.create_table('examiner_subject_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('examiner_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('times_marked', sa.Integer(), nullable=False),
    sa.Column('last_marked_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['examiner_id'], ['examiners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('examiner_id', 'subject_id', name='uq_examiner_subject_history')
    )
    op.create_index(op.f('ix_examiner_subject_history_examiner_id'), 'examiner_subject_history', ['examiner_id'], unique=False)
    op.create_index(op.f('ix_examiner_subject_history_id'), 'examiner_subject_history', ['id'], unique=False)
    op.create_index(op.f('ix_examiner_subject_history_subject_id'), 'examiner_subject_history', ['subject_id'], unique=False)
    op.create_table('examiner_teaching_experiences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('examiner_id', sa.UUID(), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('level', sa.String(length=100), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['examiner_id'], ['examiners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examiner_teaching_experiences_examiner_id'), 'examiner_teaching_experiences', ['examiner_id'], unique=False)
    op.create_index(op.f('ix_examiner_teaching_experiences_id'), 'examiner_teaching_experiences', ['id'], unique=False)
    op.create_table('examiner_training_courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('examiner_id', sa.UUID(), nullable=False),
    sa.Column('organizer', sa.String(length=255), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('place', sa.String(length=255), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('reason_for_participation', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['examiner_id'], ['examiners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examiner_training_courses_examiner_id'), 'examiner_training_courses', ['examiner_id'], unique=False)
    op.create_index(op.f('ix_examiner_training_courses_id'), 'examiner_training_courses', ['id'], unique=False)
    op.create_table('examiner_work_experiences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('examiner_id', sa.UUID(), nullable=False),
    sa.Column('occupation', sa.String(length=255), nullable=False),
    sa.Column('employer_name', sa.String(length=255), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('position_held', sa.String(length=255), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['examiner_id'], ['examiners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examiner_work_experiences_examiner_id'), 'examiner_work_experiences', ['examiner_id'], unique=False)
    op.create_index(op.f('ix_examiner_work_experiences_id'), 'examiner_work_experiences', ['id'], unique=False)
    op.create_table('subject_quotas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('quota_type', postgresql.ENUM('REGION', 'GENDER', name='quotatype', create_type=False), nullable=False),
    sa.Column('quota_key', sa.String(length=100), nullable=False),
    sa.Column('min_count', sa.Integer(), nullable=True),
    sa.Column('max_count', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['marking_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'subject_id', 'quota_type', 'quota_key', name='uq_subject_quota')
    )
    op.create_index(op.f('ix_subject_quotas_cycle_id'), 'subject_quotas', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_subject_quotas_id'), 'subject_quotas', ['id'], unique=False)
    op.create_index(op.f('ix_subject_quotas_quota_type'), 'subject_quotas', ['quota_type'], unique=False)
    op.create_index(op.f('ix_subject_quotas_subject_id'), 'subject_quotas', ['subject_id'], unique=False)
    op.create_table('allocation_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('performed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('examiner_id', sa.UUID(), nullable=True),
    sa.Column('allocation_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['examiner_allocations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cycle_id'], ['marking_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['examiner_id'], ['examiners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocation_audit_logs_action_type'), 'allocation_audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_allocation_audit_logs_allocation_id'), 'allocation_audit_logs', ['allocation_id'], unique=False)
    op.create_index(op.f('ix_allocation_audit_logs_cycle_id'), 'allocation_audit_logs', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_allocation_audit_logs_examiner_id'), 'allocation_audit_logs', ['examiner_id'], unique=False)
    op.create_index(op.f('ix_allocation_audit_logs_id'), 'allocation_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_allocation_audit_logs_performed_by_user_id'), 'allocation_audit_logs', ['performed_by_user_id'], unique=False)
    op.create_index(op.f('ix_allocation_audit_logs_subject_id'), 'allocation_audit_logs', ['subject_id'], unique=False)
    op.create_index(op.f('ix_allocation_audit_logs_timestamp'), 'allocation_audit_logs', ['timestamp'], unique=False)
    op.create_table('examiner_acceptances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('examiner_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('allocation_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', name='acceptancestatus', create_type=False), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('response_deadline', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['examiner_allocations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cycle_id'], ['marking_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['examiner_id'], ['examiners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('examiner_id', 'cycle_id', 'subject_id', name='uq_examiner_acceptance')
    )
    op.create_index(op.f('ix_examiner_acceptances_allocation_id'), 'examiner_acceptances', ['allocation_id'], unique=False)
    op.create_index(op.f('ix_examiner_acceptances_cycle_id'), 'examiner_acceptances', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_examiner_acceptances_examiner_id'), 'examiner_acceptances', ['examiner_id'], unique=False)
    op.create_index(op.f('ix_examiner_acceptances_id'), 'examiner_acceptances', ['id'], unique=False)
    op.create_index(op.f('ix_examiner_acceptances_status'), 'examiner_acceptances', ['status'], unique=False)
    op.create_index(op.f('ix_examiner_acceptances_subject_id'), 'examiner_acceptances', ['subject_id'], unique=False)
    op.create_table('examiner_application_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('document_type', postgresql.ENUM('PHOTOGRAPH', 'CERTIFICATE', 'TRANSCRIPT', name='examinerdocumenttype', create_type=False), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['examiner_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examiner_application_documents_application_id'), 'examiner_application_documents', ['application_id'], unique=False)
    op.create_index(op.f('ix_examiner_application_documents_document_type'), 'examiner_application_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_examiner_application_documents_id'), 'examiner_application_documents', ['id'], unique=False)
    op.create_table('examiner_application_examining_experiences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('examination_body', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('level', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['examiner_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examiner_application_examining_experiences_application_id'), 'examiner_application_examining_experiences', ['application_id'], unique=False)
    op.create_index(op.f('ix_examiner_application_examining_experiences_id'), 'examiner_application_examining_experiences', ['id'], unique=False)
    op.create_table('examiner_application_processing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('checked_by_user_id', sa.UUID(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('certificate_types', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('certificates_checked_by_user_id', sa.UUID(), nullable=True),
    sa.Column('certificates_checked_date', sa.Date(), nullable=True),
    sa.Column('accepted_first_invitation_date', sa.Date(), nullable=True),
    sa.Column('accepted_subject', sa.String(length=255), nullable=True),
    sa.Column('accepted_officer_user_id', sa.UUID(), nullable=True),
    sa.Column('accepted_date', sa.Date(), nullable=True),
    sa.Column('rejected_reasons', sa.Text(), nullable=True),
    sa.Column('rejected_officer_user_id', sa.UUID(), nullable=True),
    sa.Column('rejected_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['accepted_officer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['application_id'], ['examiner_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['certificates_checked_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['checked_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rejected_officer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examiner_application_processing_accepted_officer_user_id'), 'examiner_application_processing', ['accepted_officer_user_id'], unique=False)
    op.create_index(op.f('ix_examiner_application_processing_application_id'), 'examiner_application_processing', ['application_id'], unique=True)
    op.create_index(op.f('ix_examiner_application_processing_certificates_checked_by_user_id'), 'examiner_application_processing', ['certificates_checked_by_user_id'], unique=False)
    op.create_index(op.f('ix_examiner_application_processing_checked_by_user_id'), 'examiner_application_processing', ['checked_by_user_id'], unique=False)
    op.create_index(op.f('ix_examiner_application_processing_id'), 'examiner_application_processing', ['id'], unique=False)
    op.create_index(op.f('ix_examiner_application_processing_rejected_officer_user_id'), 'examiner_application_processing', ['rejected_officer_user_id'], unique=False)
    op.create_table('examiner_application_qualifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('university_college', sa.String(length=255), nullable=False),
    sa.Column('degree_diploma', sa.String(length=255), nullable=False),
    sa.Column('class_of_degree', sa.String(length=100), nullable=True),
    sa.Column('major_subjects', sa.Text(), nullable=True),
    sa.Column('date_of_award', sa.Date(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['examiner_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examiner_application_qualifications_application_id'), 'examiner_application_qualifications', ['application_id'], unique=False)
    op.create_index(op.f('ix_examiner_application_qualifications_id'), 'examiner_application_qualifications', ['id'], unique=False)
    op.create_table('examiner_application_subject_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('preference_type', postgresql.ENUM('ELECTIVE', 'CORE', 'TECHNICAL_DRAWING_BUILDING', 'TECHNICAL_DRAWING_MECHANICAL', 'PRACTICAL_COMPONENT', 'ACCESS_COURSE', name='examinersubjectpreferencetype', create_type=False), nullable=False),
    sa.Column('subject_area', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['examiner_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examiner_application_subject_preferences_application_id'), 'examiner_application_subject_preferences', ['application_id'], unique=False)
    op.create_index(op.f('ix_examiner_application_subject_preferences_id'), 'examiner_application_subject_preferences', ['id'], unique=False)
    op.create_table('examiner_application_teaching_experiences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('level', sa.String(length=100), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['examiner_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examiner_application_teaching_experiences_application_id'), 'examiner_application_teaching_experiences', ['application_id'], unique=False)
    op.create_index(op.f('ix_examiner_application_teaching_experiences_id'), 'examiner_application_teaching_experiences', ['id'], unique=False)
    op.create_table('examiner_application_training_courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('organizer', sa.String(length=255), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('place', sa.String(length=255), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('reason_for_participation', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['examiner_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examiner_application_training_courses_application_id'), 'examiner_application_training_courses', ['application_id'], unique=False)
    op.create_index(op.f('ix_examiner_application_training_courses_id'), 'examiner_application_training_courses', ['id'], unique=False)
    op.create_table('examiner_application_work_experiences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('occupation', sa.String(length=255), nullable=False),
    sa.Column('employer_name', sa.String(length=255), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('position_held', sa.String(length=255), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['examiner_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examiner_application_work_experiences_application_id'), 'examiner_application_work_experiences', ['application_id'], unique=False)
    op.create_index(op.f('ix_examiner_application_work_experiences_id'), 'examiner_application_work_experiences', ['id'], unique=False)
    op.create_table('examiner_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('recommender_name', sa.String(length=255), nullable=True),
    sa.Column('recommender_status', sa.String(length=255), nullable=True),
    sa.Column('recommender_office_address', sa.Text(), nullable=True),
    sa.Column('recommender_phone', sa.String(length=50), nullable=True),
    sa.Column('quality_ratings', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('integrity_assessment', sa.Text(), nullable=True),
    sa.Column('certification_statement', sa.Text(), nullable=True),
    sa.Column('recommendation_decision', sa.Boolean(), nullable=True),
    sa.Column('recommender_signature', sa.String(length=255), nullable=True),
    sa.Column('recommender_date', sa.Date(), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['examiner_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examiner_recommendations_application_id'), 'examiner_recommendations', ['application_id'], unique=True)
    op.create_index(op.f('ix_examiner_recommendations_completed_at'), 'examiner_recommendations', ['completed_at'], unique=False)
    op.create_index(op.f('ix_examiner_recommendations_id'), 'examiner_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_examiner_recommendations_token'), 'examiner_recommendations', ['token'], unique=True)
    op.create_index(op.f('ix_examiner_recommendations_token_expires_at'), 'examiner_recommendations', ['token_expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_examiner_recommendations_token_expires_at'), table_name='examiner_recommendations')
    op.drop_index(op.f('ix_examiner_recommendations_token'), table_name='examiner_recommendations')
    op.drop_index(op.f('ix_examiner_recommendations_id'), table_name='examiner_recommendations')
    op.drop_index(op.f('ix_examiner_recommendations_completed_at'), table_name='examiner_recommendations')
    op.drop_index(op.f('ix_examiner_recommendations_application_id'), table_name='examiner_recommendations')
    op.drop_table('examiner_recommendations')
    op.drop_index(op.f('ix_examiner_application_work_experiences_id'), table_name='examiner_application_work_experiences')
    op.drop_index(op.f('ix_examiner_application_work_experiences_application_id'), table_name='examiner_application_work_experiences')
    op.drop_table('examiner_application_work_experiences')
    op.drop_index(op.f('ix_examiner_application_training_courses_id'), table_name='examiner_application_training_courses')
    op.drop_index(op.f('ix_examiner_application_training_courses_application_id'), table_name='examiner_application_training_courses')
    op.drop_table('examiner_application_training_courses')
    op.drop_index(op.f('ix_examiner_application_teaching_experiences_id'), table_name='examiner_application_teaching_experiences')
    op.drop_index(op.f('ix_examiner_application_teaching_experiences_application_id'), table_name='examiner_application_teaching_experiences')
    op.drop_table('examiner_application_teaching_experiences')
    op.drop_index(op.f('ix_examiner_application_subject_preferences_id'), table_name='examiner_application_subject_preferences')
    op.drop_index(op.f('ix_examiner_application_subject_preferences_application_id'), table_name='examiner_application_subject_preferences')
    op.drop_table('examiner_application_subject_preferences')
    op.drop_index(op.f('ix_examiner_application_qualifications_id'), table_name='examiner_application_qualifications')
    op.drop_index(op.f('ix_examiner_application_qualifications_application_id'), table_name='examiner_application_qualifications')
    op.drop_table('examiner_application_qualifications')
    op.drop_index(op.f('ix_examiner_application_processing_rejected_officer_user_id'), table_name='examiner_application_processing')
    op.drop_index(op.f('ix_examiner_application_processing_id'), table_name='examiner_application_processing')
    op.drop_index(op.f('ix_examiner_application_processing_checked_by_user_id'), table_name='examiner_application_processing')
    op.drop_index(op.f('ix_examiner_application_processing_certificates_checked_by_user_id'), table_name='examiner_application_processing')
    op.drop_index(op.f('ix_examiner_application_processing_application_id'), table_name='examiner_application_processing')
    op.drop_index(op.f('ix_examiner_application_processing_accepted_officer_user_id'), table_name='examiner_application_processing')
    op.drop_table('examiner_application_processing')
    op.drop_index(op.f('ix_examiner_application_examining_experiences_id'), table_name='examiner_application_examining_experiences')
    op.drop_index(op.f('ix_examiner_application_examining_experiences_application_id'), table_name='examiner_application_examining_experiences')
    op.drop_table('examiner_application_examining_experiences')
    op.drop_index(op.f('ix_examiner_application_documents_id'), table_name='examiner_application_documents')
    op.drop_index(op.f('ix_examiner_application_documents_document_type'), table_name='examiner_application_documents')
    op.drop_index(op.f('ix_examiner_application_documents_application_id'), table_name='examiner_application_documents')
    op.drop_table('examiner_application_documents')
    op.drop_index(op.f('ix_examiner_acceptances_subject_id'), table_name='examiner_acceptances')
    op.drop_index(op.f('ix_examiner_acceptances_status'), table_name='examiner_acceptances')
    op.drop_index(op.f('ix_examiner_acceptances_id'), table_name='examiner_acceptances')
    op.drop_index(op.f('ix_examiner_acceptances_examiner_id'), table_name='examiner_acceptances')
    op.drop_index(op.f('ix_examiner_acceptances_cycle_id'), table_name='examiner_acceptances')
    op.drop_index(op.f('ix_examiner_acceptances_allocation_id'), table_name='examiner_acceptances')
    op.drop_table('examiner_acceptances')
    op.drop_index(op.f('ix_allocation_audit_logs_timestamp'), table_name='allocation_audit_logs')
    op.drop_index(op.f('ix_allocation_audit_logs_subject_id'), table_name='allocation_audit_logs')
    op.drop_index(op.f('ix_allocation_audit_logs_performed_by_user_id'), table_name='allocation_audit_logs')
    op.drop_index(op.f('ix_allocation_audit_logs_id'), table_name='allocation_audit_logs')
    op.drop_index(op.f('ix_allocation_audit_logs_examiner_id'), table_name='allocation_audit_logs')
    op.drop_index(op.f('ix_allocation_audit_logs_cycle_id'), table_name='allocation_audit_logs')
    op.drop_index(op.f('ix_allocation_audit_logs_allocation_id'), table_name='allocation_audit_logs')
    op.drop_index(op.f('ix_allocation_audit_logs_action_type'), table_name='allocation_audit_logs')
    op.drop_table('allocation_audit_logs')
    op.drop_index(op.f('ix_subject_quotas_subject_id'), table_name='subject_quotas')
    op.drop_index(op.f('ix_subject_quotas_quota_type'), table_name='subject_quotas')
    op.drop_index(op.f('ix_subject_quotas_id'), table_name='subject_quotas')
    op.drop_index(op.f('ix_subject_quotas_cycle_id'), table_name='subject_quotas')
    op.drop_table('subject_quotas')
    op.drop_index(op.f('ix_examiner_work_experiences_id'), table_name='examiner_work_experiences')
    op.drop_index(op.f('ix_examiner_work_experiences_examiner_id'), table_name='examiner_work_experiences')
    op.drop_table('examiner_work_experiences')
    op.drop_index(op.f('ix_examiner_training_courses_id'), table_name='examiner_training_courses')
    op.drop_index(op.f('ix_examiner_training_courses_examiner_id'), table_name='examiner_training_courses')
    op.drop_table('examiner_training_courses')
    op.drop_index(op.f('ix_examiner_teaching_experiences_id'), table_name='examiner_teaching_experiences')
    op.drop_index(op.f('ix_examiner_teaching_experiences_examiner_id'), table_name='examiner_teaching_experiences')
    op.drop_table('examiner_teaching_experiences')
    op.drop_index(op.f('ix_examiner_subject_history_subject_id'), table_name='examiner_subject_history')
    op.drop_index(op.f('ix_examiner_subject_history_id'), table_name='examiner_subject_history')
    op.drop_index(op.f('ix_examiner_subject_history_examiner_id'), table_name='examiner_subject_history')
    op.drop_table('examiner_subject_history')
    op.drop_index(op.f('ix_examiner_subject_eligibility_subject_id'), table_name='examiner_subject_eligibility')
    op.drop_index(op.f('ix_examiner_subject_eligibility_id'), table_name='examiner_subject_eligibility')
    op.drop_index(op.f('ix_examiner_subject_eligibility_examiner_id'), table_name='examiner_subject_eligibility')
    op.drop_index(op.f('ix_examiner_subject_eligibility_eligible'), table_name='examiner_subject_eligibility')
    op.drop_table('examiner_subject_eligibility')
    op.drop_index(op.f('ix_examiner_qualifications_id'), table_name='examiner_qualifications')
    op.drop_index(op.f('ix_examiner_qualifications_examiner_id'), table_name='examiner_qualifications')
    op.drop_table('examiner_qualifications')
    op.drop_index(op.f('ix_examiner_examining_experiences_id'), table_name='examiner_examining_experiences')
    op.drop_index(op.f('ix_examiner_examining_experiences_examiner_id'), table_name='examiner_examining_experiences')
    op.drop_table('examiner_examining_experiences')
    op.drop_index(op.f('ix_examiner_documents_id'), table_name='examiner_documents')
    op.drop_index(op.f('ix_examiner_documents_examiner_id'), table_name='examiner_documents')
    op.drop_index(op.f('ix_examiner_documents_document_type'), table_name='examiner_documents')
    op.drop_table('examiner_documents')
    op.drop_index(op.f('ix_examiner_applications_submitted_at'), table_name='examiner_applications')
    op.drop_index(op.f('ix_examiner_applications_status'), table_name='examiner_applications')
    op.drop_index(op.f('ix_examiner_applications_payment_status'), table_name='examiner_applications')
    op.drop_index(op.f('ix_examiner_applications_id'), table_name='examiner_applications')
    op.drop_index(op.f('ix_examiner_applications_examiner_id'), table_name='examiner_applications')
    op.drop_index(op.f('ix_examiner_applications_created_at'), table_name='examiner_applications')
    op.drop_index(op.f('ix_examiner_applications_application_number'), table_name='examiner_applications')
    op.drop_table('examiner_applications')
    op.drop_index(op.f('ix_examiner_allocations_subject_id'), table_name='examiner_allocations')
    op.drop_index(op.f('ix_examiner_allocations_id'), table_name='examiner_allocations')
    op.drop_index(op.f('ix_examiner_allocations_examiner_id'), table_name='examiner_allocations')
    op.drop_index(op.f('ix_examiner_allocations_cycle_id'), table_name='examiner_allocations')
    op.drop_index(op.f('ix_examiner_allocations_allocation_status'), table_name='examiner_allocations')
    op.drop_index(op.f('ix_examiner_allocations_allocated_by_user_id'), table_name='examiner_allocations')
    op.drop_table('examiner_allocations')
    op.drop_index(op.f('ix_marking_cycles_year'), table_name='marking_cycles')
    op.drop_index(op.f('ix_marking_cycles_subject_id'), table_name='marking_cycles')
    op.drop_index(op.f('ix_marking_cycles_status'), table_name='marking_cycles')
    op.drop_index(op.f('ix_marking_cycles_id'), table_name='marking_cycles')
    op.drop_table('marking_cycles')
    op.drop_index(op.f('ix_examiners_user_id'), table_name='examiners')
    op.drop_index(op.f('ix_examiners_status'), table_name='examiners')
    op.drop_index(op.f('ix_examiners_id'), table_name='examiners')
    op.drop_table('examiners')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.drop_table('subjects')
    sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='examinerstatus', create_type=False).drop(op.get_bind())
    sa.Enum('PHOTOGRAPH', 'CERTIFICATE', 'TRANSCRIPT', name='examinerdocumenttype', create_type=False).drop(op.get_bind())
    sa.Enum('DRAFT', 'OPEN', 'ALLOCATED', 'CLOSED', name='markingcyclestatus', create_type=False).drop(op.get_bind())
    sa.Enum('REGION', 'GENDER', name='quotatype', create_type=False).drop(op.get_bind())
    sa.Enum('APPROVED', 'WAITLISTED', 'REJECTED', name='allocationstatus', create_type=False).drop(op.get_bind())
    sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', name='acceptancestatus', create_type=False).drop(op.get_bind())
    sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', name='examinerapplicationstatus', create_type=False).drop(op.get_bind())
    sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', name='paymentstatus', create_type=False).drop(op.get_bind())
    sa.Enum('ELECTIVE', 'CORE', 'TECHNICAL_DRAWING_BUILDING', 'TECHNICAL_DRAWING_MECHANICAL', 'PRACTICAL_COMPONENT', 'ACCESS_COURSE', name='examinersubjectpreferencetype', create_type=False).drop(op.get_bind())
    # ### end Alembic commands ###
