"""Change marking cycle to examination

Revision ID: 0b1883035216
Revises: c4d5e6f7a8b9
Create Date: 2026-01-29 15:12:20.051397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '0b1883035216'
down_revision: Union[str, None] = 'c4d5e6f7a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename DB enum labels (CERTIFICATE_II, etc.) to Python enum values (Certificate II Examinations, etc.)
    op.sync_enum_values(
        enum_schema='public',
        enum_name='examtype',
        new_values=['Certificate II Examinations', 'Advance', 'Technician Part I', 'Technician Part II', 'Technician Part III', 'Diploma'],
        affected_columns=[TableReference(table_schema='public', table_name='examinations', column_name='type')],
        enum_values_to_rename=[
            ('CERTIFICATE_II', 'Certificate II Examinations'),
            ('ADVANCE', 'Advance'),
            ('TECHNICIAN_PART_I', 'Technician Part I'),
            ('TECHNICIAN_PART_II', 'Technician Part II'),
            ('TECHNICIAN_PART_III', 'Technician Part III'),
            ('DIPLOMA', 'Diploma'),
        ],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='examseries',
        new_values=['MAY/JUNE', 'NOV/DEC'],
        affected_columns=[TableReference(table_schema='public', table_name='examinations', column_name='series')],
        enum_values_to_rename=[
            ('MAY_JUNE', 'MAY/JUNE'),
            ('NOV_DEC', 'NOV/DEC'),
        ],
    )
    op.alter_column('examiner_application_teaching_experiences', 'level',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('Tertiary', 'SHS', 'JHS', 'Basic', 'Other', name='teachinglevel', native_enum=False),
               existing_nullable=True)
    op.create_index(op.f('ix_examiner_application_teaching_experiences_level'), 'examiner_application_teaching_experiences', ['level'], unique=False)
    op.alter_column('examiner_teaching_experiences', 'level',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('Tertiary', 'SHS', 'JHS', 'Basic', 'Other', name='teachinglevel', native_enum=False),
               existing_nullable=True)
    op.create_index(op.f('ix_examiner_teaching_experiences_level'), 'examiner_teaching_experiences', ['level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_examiner_teaching_experiences_level'), table_name='examiner_teaching_experiences')
    op.alter_column('examiner_teaching_experiences', 'level',
               existing_type=sa.Enum('Tertiary', 'SHS', 'JHS', 'Basic', 'Other', name='teachinglevel', native_enum=False),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_index(op.f('ix_examiner_application_teaching_experiences_level'), table_name='examiner_application_teaching_experiences')
    op.alter_column('examiner_application_teaching_experiences', 'level',
               existing_type=sa.Enum('Tertiary', 'SHS', 'JHS', 'Basic', 'Other', name='teachinglevel', native_enum=False),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.sync_enum_values(
        enum_schema='public',
        enum_name='examseries',
        new_values=['MAY_JUNE', 'NOV_DEC'],
        affected_columns=[TableReference(table_schema='public', table_name='examinations', column_name='series')],
        enum_values_to_rename=[
            ('MAY/JUNE', 'MAY_JUNE'),
            ('NOV/DEC', 'NOV_DEC'),
        ],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='examtype',
        new_values=['CERTIFICATE_II', 'ADVANCE', 'TECHNICIAN_PART_I', 'TECHNICIAN_PART_II', 'TECHNICIAN_PART_III', 'DIPLOMA'],
        affected_columns=[TableReference(table_schema='public', table_name='examinations', column_name='type')],
        enum_values_to_rename=[
            ('Certificate II Examinations', 'CERTIFICATE_II'),
            ('Advance', 'ADVANCE'),
            ('Technician Part I', 'TECHNICIAN_PART_I'),
            ('Technician Part II', 'TECHNICIAN_PART_II'),
            ('Technician Part III', 'TECHNICIAN_PART_III'),
            ('Diploma', 'DIPLOMA'),
        ],
    )
    # ### end Alembic commands ###
