"""Add region to examiner model

Revision ID: e32c8d92aa0e
Revises: 3cc69893e31e
Create Date: 2026-01-28 23:51:38.731097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e32c8d92aa0e'
down_revision: Union[str, None] = '3cc69893e31e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('Ashanti Region', 'Bono Region', 'Bono East Region', 'Ahafo Region', 'Central Region', 'Eastern Region', 'Greater Accra Region', 'Northern Region', 'North East Region', 'Savannah Region', 'Upper East Region', 'Upper West Region', 'Volta Region', 'Oti Region', 'Western Region', 'Western North Region', name='ghanaregion').create(op.get_bind())
    op.add_column('examiner_applications', sa.Column('region', sa.Enum('Ashanti Region', 'Bono Region', 'Bono East Region', 'Ahafo Region', 'Central Region', 'Eastern Region', 'Greater Accra Region', 'Northern Region', 'North East Region', 'Savannah Region', 'Upper East Region', 'Upper West Region', 'Volta Region', 'Oti Region', 'Western Region', 'Western North Region', name='ghanaregion'), nullable=False))
    op.create_index(op.f('ix_examiner_applications_region'), 'examiner_applications', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_examiner_applications_region'), table_name='examiner_applications')
    op.drop_column('examiner_applications', 'region')
    sa.Enum('Ashanti Region', 'Bono Region', 'Bono East Region', 'Ahafo Region', 'Central Region', 'Eastern Region', 'Greater Accra Region', 'Northern Region', 'North East Region', 'Savannah Region', 'Upper East Region', 'Upper West Region', 'Volta Region', 'Oti Region', 'Western Region', 'Western North Region', name='ghanaregion').drop(op.get_bind())
    # ### end Alembic commands ###
