"""Add examiners models

Revision ID: 5afd55a452a4
Revises: e1f2a3b4c5d6
Create Date: 2026-04-12 23:24:42.366243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5afd55a452a4'
down_revision: Union[str, Sequence[str], None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('DRAFT', 'OPTIMAL', 'INFEASIBLE', 'TIMEOUT', 'ERROR', name='allocationrunstatus').create(op.get_bind())
    sa.Enum('CHIEF', 'ASSISTANT', 'TEAM_LEADER', name='examinertype').create(op.get_bind())
    op.create_table('allocation_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('examination_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('paper_number', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['examination_id'], ['examinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocation_campaigns_examination_id'), 'allocation_campaigns', ['examination_id'], unique=False)
    op.create_index(op.f('ix_allocation_campaigns_subject_id'), 'allocation_campaigns', ['subject_id'], unique=False)
    op.create_table('allocation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'OPTIMAL', 'INFEASIBLE', 'TIMEOUT', 'ERROR', name='allocationrunstatus', create_type=False), nullable=False),
    sa.Column('objective_value', sa.Float(), nullable=True),
    sa.Column('solver_message', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('solver_stats', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['allocation_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocation_runs_campaign_id'), 'allocation_runs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_allocation_runs_created_by_id'), 'allocation_runs', ['created_by_id'], unique=False)
    op.create_table('examiners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('examiner_type', postgresql.ENUM('CHIEF', 'ASSISTANT', 'TEAM_LEADER', name='examinertype', create_type=False), nullable=False),
    sa.Column('home_zone', postgresql.ENUM('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', name='zone', create_type=False), nullable=True),
    sa.Column('deviation_weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('deviation_weight IS NULL OR deviation_weight > 0', name='ck_examiner_deviation_weight_positive'),
    sa.ForeignKeyConstraint(['campaign_id'], ['allocation_campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examiners_campaign_id'), 'examiners', ['campaign_id'], unique=False)
    op.create_table('scripts_allocation_quotas',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('examiner_type', postgresql.ENUM('CHIEF', 'ASSISTANT', 'TEAM_LEADER', name='examinertype', create_type=False), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('quota_booklets', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quota_booklets >= 0', name='ck_scripts_allocation_quota_nonneg'),
    sa.ForeignKeyConstraint(['campaign_id'], ['allocation_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', 'examiner_type', 'subject_id')
    )
    op.create_table('examiner_allowed_zones',
    sa.Column('examiner_id', sa.UUID(), nullable=False),
    sa.Column('zone', postgresql.ENUM('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', name='zone', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['examiner_id'], ['examiners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('examiner_id', 'zone')
    )
    op.create_table('examiner_subjects',
    sa.Column('examiner_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['examiner_id'], ['examiners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('examiner_id', 'subject_id')
    )
    op.create_table('allocation_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('allocation_run_id', sa.UUID(), nullable=False),
    sa.Column('script_envelope_id', sa.UUID(), nullable=False),
    sa.Column('examiner_id', sa.UUID(), nullable=False),
    sa.Column('booklet_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('booklet_count >= 0', name='ck_allocation_assignment_booklet_count'),
    sa.ForeignKeyConstraint(['allocation_run_id'], ['allocation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['examiner_id'], ['examiners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['script_envelope_id'], ['script_envelopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('allocation_run_id', 'script_envelope_id', name='uq_allocation_assignment_run_envelope')
    )
    op.create_index(op.f('ix_allocation_assignments_allocation_run_id'), 'allocation_assignments', ['allocation_run_id'], unique=False)
    op.create_index(op.f('ix_allocation_assignments_examiner_id'), 'allocation_assignments', ['examiner_id'], unique=False)
    op.create_index(op.f('ix_allocation_assignments_script_envelope_id'), 'allocation_assignments', ['script_envelope_id'], unique=False)
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    # # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    # op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.drop_index(op.f('ix_allocation_assignments_script_envelope_id'), table_name='allocation_assignments')
    op.drop_index(op.f('ix_allocation_assignments_examiner_id'), table_name='allocation_assignments')
    op.drop_index(op.f('ix_allocation_assignments_allocation_run_id'), table_name='allocation_assignments')
    op.drop_table('allocation_assignments')
    op.drop_table('examiner_subjects')
    op.drop_table('examiner_allowed_zones')
    op.drop_table('scripts_allocation_quotas')
    op.drop_index(op.f('ix_examiners_campaign_id'), table_name='examiners')
    op.drop_table('examiners')
    op.drop_index(op.f('ix_allocation_runs_created_by_id'), table_name='allocation_runs')
    op.drop_index(op.f('ix_allocation_runs_campaign_id'), table_name='allocation_runs')
    op.drop_table('allocation_runs')
    op.drop_index(op.f('ix_allocation_campaigns_subject_id'), table_name='allocation_campaigns')
    op.drop_index(op.f('ix_allocation_campaigns_examination_id'), table_name='allocation_campaigns')
    op.drop_table('allocation_campaigns')
    sa.Enum('CHIEF', 'ASSISTANT', 'TEAM_LEADER', name='examinertype').drop(op.get_bind())
    sa.Enum('DRAFT', 'OPTIMAL', 'INFEASIBLE', 'TIMEOUT', 'ERROR', name='allocationrunstatus').drop(op.get_bind())
    # ### end Alembic commands ###
