"""Add school  model

Revision ID: f9e91da30963
Revises: 2a3d8457496a
Create Date: 2026-04-03 15:16:59.041560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9e91da30963'
down_revision: Union[str, Sequence[str], None] = '2a3d8457496a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PRIVATE', 'PUBLIC', name='schooltype').create(op.get_bind())
    sa.Enum('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', name='zone').create(op.get_bind())
    sa.Enum('ASHANTI', 'BONO', 'BONO_EAST', 'AHAFO', 'CENTRAL', 'EASTERN', 'GREATER_ACCRA', 'NORTHERN', 'NORTH_EAST', 'SAVANNAH', 'UPPER_EAST', 'UPPER_WEST', 'VOLTA', 'OTI', 'WESTERN', 'WESTERN_NORTH', name='region').create(op.get_bind())
    op.create_table('schools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', postgresql.ENUM('ASHANTI', 'BONO', 'BONO_EAST', 'AHAFO', 'CENTRAL', 'EASTERN', 'GREATER_ACCRA', 'NORTHERN', 'NORTH_EAST', 'SAVANNAH', 'UPPER_EAST', 'UPPER_WEST', 'VOLTA', 'OTI', 'WESTERN', 'WESTERN_NORTH', name='region', create_type=False), nullable=False),
    sa.Column('zone', postgresql.ENUM('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', name='zone', create_type=False), nullable=False),
    sa.Column('school_type', postgresql.ENUM('PRIVATE', 'PUBLIC', name='schooltype', create_type=False), nullable=True),
    sa.Column('is_private_examination_center', sa.Boolean(), nullable=False),
    sa.Column('writes_at_center_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['writes_at_center_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_code'), 'schools', ['code'], unique=True)
    op.create_index(op.f('ix_schools_writes_at_center_id'), 'schools', ['writes_at_center_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schools_writes_at_center_id'), table_name='schools')
    op.drop_index(op.f('ix_schools_code'), table_name='schools')
    op.drop_table('schools')
    sa.Enum('ASHANTI', 'BONO', 'BONO_EAST', 'AHAFO', 'CENTRAL', 'EASTERN', 'GREATER_ACCRA', 'NORTHERN', 'NORTH_EAST', 'SAVANNAH', 'UPPER_EAST', 'UPPER_WEST', 'VOLTA', 'OTI', 'WESTERN', 'WESTERN_NORTH', name='region').drop(op.get_bind())
    sa.Enum('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', name='zone').drop(op.get_bind())
    sa.Enum('PRIVATE', 'PUBLIC', name='schooltype').drop(op.get_bind())
    # ### end Alembic commands ###
