"""Add script envelope  models

Revision ID: a3b40672f2cf
Revises: bde74f910c34
Create Date: 2026-04-05 11:42:44.312211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3b40672f2cf'
down_revision: Union[str, Sequence[str], None] = 'bde74f910c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('script_packing_series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('examination_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('paper_number', sa.SmallInteger(), nullable=False),
    sa.Column('series_number', sa.SmallInteger(), nullable=False),
    sa.Column('scripts_per_envelope', sa.Integer(), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('paper_number >= 1', name='ck_script_packing_paper_number'),
    sa.CheckConstraint('scripts_per_envelope >= 1', name='ck_script_packing_scripts_per_envelope'),
    sa.CheckConstraint('series_number >= 1 AND series_number <= 6', name='ck_script_packing_series_number'),
    sa.ForeignKeyConstraint(['examination_id'], ['examinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('examination_id', 'school_id', 'subject_id', 'paper_number', 'series_number', name='uq_script_packing_series_exam_school_subject_paper_series')
    )
    op.create_index(op.f('ix_script_packing_series_examination_id'), 'script_packing_series', ['examination_id'], unique=False)
    op.create_index(op.f('ix_script_packing_series_school_id'), 'script_packing_series', ['school_id'], unique=False)
    op.create_index(op.f('ix_script_packing_series_subject_id'), 'script_packing_series', ['subject_id'], unique=False)
    op.create_index(op.f('ix_script_packing_series_updated_by_id'), 'script_packing_series', ['updated_by_id'], unique=False)
    op.create_table('script_envelopes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('packing_series_id', sa.UUID(), nullable=False),
    sa.Column('envelope_number', sa.Integer(), nullable=False),
    sa.Column('booklet_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('booklet_count >= 0', name='ck_script_envelope_booklet_count'),
    sa.CheckConstraint('envelope_number >= 1', name='ck_script_envelope_number'),
    sa.ForeignKeyConstraint(['packing_series_id'], ['script_packing_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('packing_series_id', 'envelope_number', name='uq_script_envelope_series_number')
    )
    op.create_index(op.f('ix_script_envelopes_packing_series_id'), 'script_envelopes', ['packing_series_id'], unique=False)
    #op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    #op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    #op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.drop_index(op.f('ix_script_envelopes_packing_series_id'), table_name='script_envelopes')
    op.drop_table('script_envelopes')
    op.drop_index(op.f('ix_script_packing_series_updated_by_id'), table_name='script_packing_series')
    op.drop_index(op.f('ix_script_packing_series_subject_id'), table_name='script_packing_series')
    op.drop_index(op.f('ix_script_packing_series_school_id'), table_name='script_packing_series')
    op.drop_index(op.f('ix_script_packing_series_examination_id'), table_name='script_packing_series')
    op.drop_table('script_packing_series')
    # ### end Alembic commands ###
