"""Add question control models

Revision ID: fb4ac65374b0
Revises: c3d9f0a12e55
Create Date: 2026-04-06 16:03:01.957799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb4ac65374b0'
down_revision: Union[str, Sequence[str], None] = 'c3d9f0a12e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_paper_control',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('examination_id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('paper_number', sa.SmallInteger(), nullable=False),
    sa.Column('series_number', sa.SmallInteger(), nullable=False),
    sa.Column('copies_received', sa.Integer(), nullable=False),
    sa.Column('copies_used', sa.Integer(), nullable=False),
    sa.Column('copies_to_library', sa.Integer(), nullable=False),
    sa.Column('copies_remaining', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('copies_received >= 0', name='ck_question_paper_control_received'),
    sa.CheckConstraint('copies_remaining >= 0', name='ck_question_paper_control_remaining'),
    sa.CheckConstraint('copies_to_library >= 0', name='ck_question_paper_control_library'),
    sa.CheckConstraint('copies_used >= 0', name='ck_question_paper_control_used'),
    sa.CheckConstraint('paper_number >= 1', name='ck_question_paper_control_paper'),
    sa.CheckConstraint('series_number >= 1 AND series_number <= 32767', name='ck_question_paper_control_series'),
    sa.ForeignKeyConstraint(['center_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['examination_id'], ['examinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('examination_id', 'center_id', 'subject_id', 'paper_number', 'series_number', name='uq_question_paper_control_exam_center_subject_paper_series')
    )
    op.create_index(op.f('ix_question_paper_control_center_id'), 'question_paper_control', ['center_id'], unique=False)
    op.create_index(op.f('ix_question_paper_control_examination_id'), 'question_paper_control', ['examination_id'], unique=False)
    op.create_index(op.f('ix_question_paper_control_subject_id'), 'question_paper_control', ['subject_id'], unique=False)
    op.create_index(op.f('ix_question_paper_control_updated_by_id'), 'question_paper_control', ['updated_by_id'], unique=False)
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    # op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.drop_index(op.f('ix_question_paper_control_updated_by_id'), table_name='question_paper_control')
    op.drop_index(op.f('ix_question_paper_control_subject_id'), table_name='question_paper_control')
    op.drop_index(op.f('ix_question_paper_control_examination_id'), table_name='question_paper_control')
    op.drop_index(op.f('ix_question_paper_control_center_id'), table_name='question_paper_control')
    op.drop_table('question_paper_control')
    # ### end Alembic commands ###
