"""Add candidate registration models

Revision ID: e8513c93b555
Revises: a3b40672f2cf
Create Date: 2026-04-05 18:22:53.484641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8513c93b555'
down_revision: Union[str, Sequence[str], None] = 'a3b40672f2cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('examination_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('examination_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('programme_id', sa.Integer(), nullable=True),
    sa.Column('registration_number', sa.String(length=50), nullable=False),
    sa.Column('index_number', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('registration_status', sa.String(length=32), nullable=True),
    sa.Column('source_candidate_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['examination_id'], ['examinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('examination_id', 'registration_number', name='uq_examination_candidate_reg_number')
    )
    op.create_index(op.f('ix_examination_candidates_examination_id'), 'examination_candidates', ['examination_id'], unique=False)
    op.create_index(op.f('ix_examination_candidates_index_number'), 'examination_candidates', ['index_number'], unique=False)
    op.create_index(op.f('ix_examination_candidates_programme_id'), 'examination_candidates', ['programme_id'], unique=False)
    op.create_index(op.f('ix_examination_candidates_school_id'), 'examination_candidates', ['school_id'], unique=False)
    op.create_index(op.f('ix_examination_candidates_source_candidate_id'), 'examination_candidates', ['source_candidate_id'], unique=False)
    op.create_table('examination_candidate_subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('examination_candidate_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('subject_code', sa.String(length=50), nullable=False),
    sa.Column('subject_name', sa.String(length=255), nullable=False),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['examination_candidate_id'], ['examination_candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examination_candidate_subjects_examination_candidate_id'), 'examination_candidate_subjects', ['examination_candidate_id'], unique=False)
    op.create_index(op.f('ix_examination_candidate_subjects_subject_id'), 'examination_candidate_subjects', ['subject_id'], unique=False)
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    # op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.drop_index(op.f('ix_examination_candidate_subjects_subject_id'), table_name='examination_candidate_subjects')
    op.drop_index(op.f('ix_examination_candidate_subjects_examination_candidate_id'), table_name='examination_candidate_subjects')
    op.drop_table('examination_candidate_subjects')
    op.drop_index(op.f('ix_examination_candidates_source_candidate_id'), table_name='examination_candidates')
    op.drop_index(op.f('ix_examination_candidates_school_id'), table_name='examination_candidates')
    op.drop_index(op.f('ix_examination_candidates_programme_id'), table_name='examination_candidates')
    op.drop_index(op.f('ix_examination_candidates_index_number'), table_name='examination_candidates')
    op.drop_index(op.f('ix_examination_candidates_examination_id'), table_name='examination_candidates')
    op.drop_table('examination_candidates')
    # ### end Alembic commands ###
