"""Add programme and subject models

Revision ID: e4ed5f71b375
Revises: f9e91da30963
Create Date: 2026-04-04 13:31:13.903512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4ed5f71b375'
down_revision: Union[str, Sequence[str], None] = 'f9e91da30963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('CORE', 'ELECTIVE', name='subjecttype').create(op.get_bind())
    op.create_table('programmes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programmes_code'), 'programmes', ['code'], unique=True)
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('original_code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject_type', postgresql.ENUM('CORE', 'ELECTIVE', name='subjecttype', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=True)
    op.create_index(op.f('ix_subjects_original_code'), 'subjects', ['original_code'], unique=True)
    op.create_table('programme_subjects',
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('is_compulsory', sa.Boolean(), nullable=True),
    sa.Column('choice_group_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('programme_id', 'subject_id'),
    sa.UniqueConstraint('programme_id', 'subject_id', name='uq_programme_subject')
    )
    op.create_index(op.f('ix_programme_subjects_choice_group_id'), 'programme_subjects', ['choice_group_id'], unique=False)
    op.create_table('school_programmes',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('school_id', 'programme_id'),
    sa.UniqueConstraint('school_id', 'programme_id', name='uq_school_programme')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school_programmes')
    op.drop_index(op.f('ix_programme_subjects_choice_group_id'), table_name='programme_subjects')
    op.drop_table('programme_subjects')
    op.drop_index(op.f('ix_subjects_original_code'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_programmes_code'), table_name='programmes')
    op.drop_table('programmes')
    sa.Enum('CORE', 'ELECTIVE', name='subjecttype').drop(op.get_bind())
    # ### end Alembic commands ###
