"""Add depot models

Revision ID: a7aef5e0200a
Revises: fb4ac65374b0
Create Date: 2026-04-07 22:10:38.481116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'a7aef5e0200a'
down_revision: Union[str, Sequence[str], None] = 'fb4ac65374b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_depots_code'), 'depots', ['code'], unique=True)
    #op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    op.add_column('question_paper_control', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.add_column('question_paper_control', sa.Column('verified_by_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_question_paper_control_verified_by_id'), 'question_paper_control', ['verified_by_id'], unique=False)
    op.create_foreign_key(None, 'question_paper_control', 'users', ['verified_by_id'], ['id'], ondelete='SET NULL')
    #op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    op.add_column('schools', sa.Column('depot_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_schools_depot_id'), 'schools', ['depot_id'], unique=False)
    op.create_foreign_key(None, 'schools', 'depots', ['depot_id'], ['id'], ondelete='SET NULL')
    op.add_column('script_packing_series', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.add_column('script_packing_series', sa.Column('verified_by_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_script_packing_series_verified_by_id'), 'script_packing_series', ['verified_by_id'], unique=False)
    op.create_foreign_key(None, 'script_packing_series', 'users', ['verified_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('depot_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_depot_id'), 'users', ['depot_id'], unique=False)
    op.create_foreign_key(None, 'users', 'depots', ['depot_id'], ['id'], ondelete='SET NULL')
    op.sync_enum_values(
        enum_schema='public',
        enum_name='userrole',
        new_values=['SUPER_ADMIN', 'SUPERVISOR', 'INSPECTOR', 'DEPOT_KEEPER'],
        affected_columns=[TableReference(table_schema='public', table_name='users', column_name='role')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='userrole',
        new_values=['SUPER_ADMIN', 'SUPERVISOR', 'INSPECTOR'],
        affected_columns=[TableReference(table_schema='public', table_name='users', column_name='role')],
        enum_values_to_rename=[],
    )
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_depot_id'), table_name='users')
    op.drop_column('users', 'depot_id')
    op.drop_constraint(None, 'script_packing_series', type_='foreignkey')
    op.drop_index(op.f('ix_script_packing_series_verified_by_id'), table_name='script_packing_series')
    op.drop_column('script_packing_series', 'verified_by_id')
    op.drop_column('script_packing_series', 'verified_at')
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.drop_index(op.f('ix_schools_depot_id'), table_name='schools')
    op.drop_column('schools', 'depot_id')
    #op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    op.drop_constraint(None, 'question_paper_control', type_='foreignkey')
    op.drop_index(op.f('ix_question_paper_control_verified_by_id'), table_name='question_paper_control')
    op.drop_column('question_paper_control', 'verified_by_id')
    op.drop_column('question_paper_control', 'verified_at')
    #op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.drop_index(op.f('ix_depots_code'), table_name='depots')
    op.drop_table('depots')
    # ### end Alembic commands ###
