"""add category to programme model

Revision ID: d0cef223d1e7
Revises: 36e212802742
Create Date: 2025-12-20 17:37:30.407618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0cef223d1e7'
down_revision: Union[str, Sequence[str], None] = '36e212802742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    op.add_column('programmes', sa.Column('exam_type', sa.Enum('CERTIFICATE_II', 'CBT', name='examtype'), nullable=True))
    #op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    op.drop_column('programmes', 'exam_type')
    op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    # ### end Alembic commands ###
