"""Add photo model

Revision ID: eb48a43435ba
Revises: 43bd44712f95
Create Date: 2025-12-30 11:33:47.090244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb48a43435ba'
down_revision: Union[str, Sequence[str], None] = '43bd44712f95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_photos_candidate_id'), 'candidate_photos', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_photos_checksum'), 'candidate_photos', ['checksum'], unique=False)
    op.create_index(op.f('ix_candidate_photos_is_active'), 'candidate_photos', ['is_active'], unique=False)
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    # # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.drop_index(op.f('ix_candidate_photos_is_active'), table_name='candidate_photos')
    op.drop_index(op.f('ix_candidate_photos_checksum'), table_name='candidate_photos')
    op.drop_index(op.f('ix_candidate_photos_candidate_id'), table_name='candidate_photos')
    op.drop_table('candidate_photos')
    # ### end Alembic commands ###
