"""update document model

Revision ID: 29e48f44f608
Revises: 53efa0babea8
Create Date: 2025-12-25 10:12:24.762384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29e48f44f608'
down_revision: Union[str, Sequence[str], None] = '53efa0babea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('scores_extraction_methods', sa.ARRAY(sa.Enum('AUTOMATED_EXTRACTION', 'MANUAL_TRANSCRIPTION_DIGITAL', 'MANUAL_ENTRY_PHYSICAL', name='dataextractionmethod')), nullable=True))
    op.drop_column('documents', 'scores_extraction_method')
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    # # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.add_column('documents', sa.Column('scores_extraction_method', postgresql.ENUM('AUTOMATED_EXTRACTION', 'MANUAL_TRANSCRIPTION_DIGITAL', 'MANUAL_ENTRY_PHYSICAL', name='dataextractionmethod'), autoincrement=False, nullable=True))
    op.drop_column('documents', 'scores_extraction_methods')
    # ### end Alembic commands ###
