"""Update subjectscore and document model

Revision ID: 51a6caf5f269
Revises: 689ce90bd990
Create Date: 2025-12-24 21:31:35.851243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a6caf5f269'
down_revision: Union[str, Sequence[str], None] = '689ce90bd990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'scores_extraction_method',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=40),
               existing_nullable=True)
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])

    # Create the enum type first (if it doesn't exist)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE dataextractionmethod AS ENUM ('AUTOMATED_EXTRACTION', 'MANUAL_TRANSCRIPTION_DIGITAL', 'MANUAL_ENTRY_PHYSICAL');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)

    # Now add columns using the enum type
    op.add_column('subject_scores', sa.Column('obj_extraction_method', sa.Enum('AUTOMATED_EXTRACTION', 'MANUAL_TRANSCRIPTION_DIGITAL', 'MANUAL_ENTRY_PHYSICAL', name='dataextractionmethod', create_type=False), nullable=True))
    op.add_column('subject_scores', sa.Column('essay_extraction_method', sa.Enum('AUTOMATED_EXTRACTION', 'MANUAL_TRANSCRIPTION_DIGITAL', 'MANUAL_ENTRY_PHYSICAL', name='dataextractionmethod', create_type=False), nullable=True))
    op.add_column('subject_scores', sa.Column('pract_extraction_method', sa.Enum('AUTOMATED_EXTRACTION', 'MANUAL_TRANSCRIPTION_DIGITAL', 'MANUAL_ENTRY_PHYSICAL', name='dataextractionmethod', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject_scores', 'pract_extraction_method')
    op.drop_column('subject_scores', 'essay_extraction_method')
    op.drop_column('subject_scores', 'obj_extraction_method')

    # Drop the enum type (if it exists)
    op.execute("DROP TYPE IF EXISTS dataextractionmethod")

    op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.alter_column('documents', 'scores_extraction_method',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
