"""Add process tracking model

Revision ID: 43bd44712f95
Revises: 7a4aa17f0293
Create Date: 2025-12-29 21:29:03.023085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43bd44712f95'
down_revision: Union[str, Sequence[str], None] = '7a4aa17f0293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('process_type', sa.Enum('SERIALIZATION', 'EXCEL_EXPORT_CORE', 'EXCEL_EXPORT_ELECTIVES', 'SCORE_SHEET_GENERATION', 'PDF_GENERATION', name='processtype'), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='processstatus'), nullable=False),
    sa.Column('process_metadata', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_tracking_created_at'), 'process_tracking', ['created_at'], unique=False)
    op.create_index(op.f('ix_process_tracking_exam_id'), 'process_tracking', ['exam_id'], unique=False)
    op.create_index(op.f('ix_process_tracking_process_type'), 'process_tracking', ['process_type'], unique=False)
    op.create_index(op.f('ix_process_tracking_school_id'), 'process_tracking', ['school_id'], unique=False)
    op.create_index(op.f('ix_process_tracking_status'), 'process_tracking', ['status'], unique=False)
    op.create_index(op.f('ix_process_tracking_subject_id'), 'process_tracking', ['subject_id'], unique=False)
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    # # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.drop_index(op.f('ix_process_tracking_subject_id'), table_name='process_tracking')
    op.drop_index(op.f('ix_process_tracking_status'), table_name='process_tracking')
    op.drop_index(op.f('ix_process_tracking_school_id'), table_name='process_tracking')
    op.drop_index(op.f('ix_process_tracking_process_type'), table_name='process_tracking')
    op.drop_index(op.f('ix_process_tracking_exam_id'), table_name='process_tracking')
    op.drop_index(op.f('ix_process_tracking_created_at'), table_name='process_tracking')
    op.drop_table('process_tracking')
    # ### end Alembic commands ###
