"""reset

Revision ID: 36e212802742
Revises:
Create Date: 2025-12-20 17:10:31.451834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e212802742'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.Enum('CERTIFICATE_II', 'CBT', name='examtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('series', sa.Enum('MAY_JUNE', 'NOV_DEC', name='examseries'), nullable=False),
    sa.Column('number_of_series', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_type', 'series', 'year', name='uq_exam_exam_type_series_year')
    )
    op.create_table('programmes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programmes_code'), 'programmes', ['code'], unique=True)
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.Enum('ASHANTI', 'BONO', 'BONO_EAST', 'AHAFO', 'CENTRAL', 'EASTERN', 'GREATER_ACCRA', 'NORTHERN', 'NORTH_EAST', 'SAVANNAH', 'UPPER_EAST', 'UPPER_WEST', 'VOLTA', 'OTI', 'WESTERN', 'WESTERN_NORTH', name='schoolregion'), nullable=False),
    sa.Column('zone', sa.Enum('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', name='schoolzone'), nullable=False),
    sa.Column('school_type', sa.Enum('PRIVATE', 'PUBLIC', name='schooltype'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_code'), 'schools', ['code'], unique=True)
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject_type', sa.Enum('CORE', 'ELECTIVE', name='subjecttype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=True)
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('index_number', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_index_number'), 'candidates', ['index_number'], unique=False)
    op.create_index(op.f('ix_candidates_programme_id'), 'candidates', ['programme_id'], unique=False)
    op.create_index(op.f('ix_candidates_school_id'), 'candidates', ['school_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.String(length=1), nullable=True),
    sa.Column('subject_series', sa.String(length=1), nullable=True),
    sa.Column('sheet_number', sa.String(length=2), nullable=True),
    sa.Column('extracted_id', sa.String(length=13), nullable=True),
    sa.Column('id_extraction_method', sa.String(length=20), nullable=True),
    sa.Column('id_extraction_confidence', sa.Float(), nullable=True),
    sa.Column('id_extraction_status', sa.String(length=20), nullable=False),
    sa.Column('id_extracted_at', sa.DateTime(), nullable=True),
    sa.Column('scores_extraction_data', sa.JSON(), nullable=True),
    sa.Column('scores_extraction_status', sa.String(length=20), nullable=False),
    sa.Column('scores_extraction_method', sa.String(length=20), nullable=True),
    sa.Column('scores_extraction_confidence', sa.Float(), nullable=True),
    sa.Column('scores_extracted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_checksum'), 'documents', ['checksum'], unique=False)
    op.create_index(op.f('ix_documents_exam_id'), 'documents', ['exam_id'], unique=False)
    op.create_index(op.f('ix_documents_extracted_id'), 'documents', ['extracted_id'], unique=False)
    op.create_index(op.f('ix_documents_school_id'), 'documents', ['school_id'], unique=False)
    op.create_index(op.f('ix_documents_subject_id'), 'documents', ['subject_id'], unique=False)
    op.create_table('exam_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('obj_pct', sa.Float(), nullable=True),
    sa.Column('essay_pct', sa.Float(), nullable=True),
    sa.Column('pract_pct', sa.Float(), nullable=True),
    sa.Column('obj_max_score', sa.Float(), nullable=True),
    sa.Column('essay_max_score', sa.Float(), nullable=True),
    sa.Column('pract_max_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'subject_id', name='uq_exam_subject')
    )
    op.create_index(op.f('ix_exam_subjects_exam_id'), 'exam_subjects', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_subjects_subject_id'), 'exam_subjects', ['subject_id'], unique=False)
    op.create_table('programme_subjects',
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('is_compulsory', sa.Boolean(), nullable=True, comment='True for compulsory core subjects, False for optional core subjects, NULL for electives'),
    sa.Column('choice_group_id', sa.Integer(), nullable=True, comment='Groups optional core subjects together. Subjects in the same group require selecting exactly one'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('programme_id', 'subject_id'),
    sa.UniqueConstraint('programme_id', 'subject_id', name='uq_programme_subject')
    )
    op.create_index(op.f('ix_programme_subjects_choice_group_id'), 'programme_subjects', ['choice_group_id'], unique=False)
    op.create_table('school_programmes',
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('school_id', 'programme_id'),
    sa.UniqueConstraint('school_id', 'programme_id', name='uq_school_programme')
    )
    op.create_table('exam_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('index_number', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'exam_id', name='uq_candidate_exam'),
    sa.UniqueConstraint('index_number', 'exam_id', name='uq_index_number_exam')
    )
    op.create_index(op.f('ix_exam_registrations_candidate_id'), 'exam_registrations', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_exam_registrations_exam_id'), 'exam_registrations', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_registrations_index_number'), 'exam_registrations', ['index_number'], unique=False)
    op.create_table('subject_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_registration_id', sa.Integer(), nullable=False),
    sa.Column('exam_subject_id', sa.Integer(), nullable=False),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_registration_id'], ['exam_registrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_subject_id'], ['exam_subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_registration_id', 'exam_subject_id', name='uq_exam_registration_exam_subject')
    )
    op.create_index(op.f('ix_subject_registrations_exam_registration_id'), 'subject_registrations', ['exam_registration_id'], unique=False)
    op.create_index(op.f('ix_subject_registrations_exam_subject_id'), 'subject_registrations', ['exam_subject_id'], unique=False)
    op.create_table('subject_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_registration_id', sa.Integer(), nullable=False),
    sa.Column('obj_raw_score', sa.String(length=10), nullable=True),
    sa.Column('essay_raw_score', sa.String(length=10), nullable=True),
    sa.Column('pract_raw_score', sa.String(length=10), nullable=True),
    sa.Column('obj_normalized', sa.Float(), nullable=True),
    sa.Column('essay_normalized', sa.Float(), nullable=True),
    sa.Column('pract_normalized', sa.Float(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('obj_document_id', sa.String(length=13), nullable=True),
    sa.Column('essay_document_id', sa.String(length=13), nullable=True),
    sa.Column('pract_document_id', sa.String(length=13), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_registration_id'], ['subject_registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_scores_essay_document_id'), 'subject_scores', ['essay_document_id'], unique=False)
    op.create_index(op.f('ix_subject_scores_obj_document_id'), 'subject_scores', ['obj_document_id'], unique=False)
    op.create_index(op.f('ix_subject_scores_pract_document_id'), 'subject_scores', ['pract_document_id'], unique=False)
    op.create_index(op.f('ix_subject_scores_subject_registration_id'), 'subject_scores', ['subject_registration_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subject_scores_subject_registration_id'), table_name='subject_scores')
    op.drop_index(op.f('ix_subject_scores_pract_document_id'), table_name='subject_scores')
    op.drop_index(op.f('ix_subject_scores_obj_document_id'), table_name='subject_scores')
    op.drop_index(op.f('ix_subject_scores_essay_document_id'), table_name='subject_scores')
    op.drop_table('subject_scores')
    op.drop_index(op.f('ix_subject_registrations_exam_subject_id'), table_name='subject_registrations')
    op.drop_index(op.f('ix_subject_registrations_exam_registration_id'), table_name='subject_registrations')
    op.drop_table('subject_registrations')
    op.drop_index(op.f('ix_exam_registrations_index_number'), table_name='exam_registrations')
    op.drop_index(op.f('ix_exam_registrations_exam_id'), table_name='exam_registrations')
    op.drop_index(op.f('ix_exam_registrations_candidate_id'), table_name='exam_registrations')
    op.drop_table('exam_registrations')
    op.drop_table('school_programmes')
    op.drop_index(op.f('ix_programme_subjects_choice_group_id'), table_name='programme_subjects')
    op.drop_table('programme_subjects')
    op.drop_index(op.f('ix_exam_subjects_subject_id'), table_name='exam_subjects')
    op.drop_index(op.f('ix_exam_subjects_exam_id'), table_name='exam_subjects')
    op.drop_table('exam_subjects')
    op.drop_index(op.f('ix_documents_subject_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_school_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_extracted_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_exam_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_checksum'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_candidates_school_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_programme_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_index_number'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_schools_code'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_programmes_code'), table_name='programmes')
    op.drop_table('programmes')
    op.drop_table('exams')
    # ### end Alembic commands ###
