"""Update unMatchedExtractionRecord model

Revision ID: f8c9d86daede
Revises: 498707f3cb81
Create Date: 2025-12-25 16:23:16.698821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c9d86daede'
down_revision: Union[str, Sequence[str], None] = '498707f3cb81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    op.add_column('unmatched_extraction_records', sa.Column('sn', sa.Integer(), nullable=True))
    op.add_column('unmatched_extraction_records', sa.Column('extraction_method', sa.Enum('AUTOMATED_EXTRACTION', 'MANUAL_TRANSCRIPTION_DIGITAL', 'MANUAL_ENTRY_PHYSICAL', name='dataextractionmethod'), nullable=False))
    op.create_index(op.f('ix_unmatched_extraction_records_sn'), 'unmatched_extraction_records', ['sn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unmatched_extraction_records_sn'), table_name='unmatched_extraction_records')
    op.drop_column('unmatched_extraction_records', 'extraction_method')
    op.drop_column('unmatched_extraction_records', 'sn')
    op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    # ### end Alembic commands ###
