"""add exam_type to subject

Revision ID: e0e8601a3da0
Revises: 0a636d9e6502
Create Date: 2025-12-21 01:18:16.547588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0e8601a3da0'
down_revision: Union[str, Sequence[str], None] = '0a636d9e6502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    #op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    op.add_column('subjects', sa.Column('exam_type', sa.Enum('CERTIFICATE_II', 'CBT', name='examtype'), nullable=False))
    op.create_index(op.f('ix_subjects_exam_type'), 'subjects', ['exam_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subjects_exam_type'), table_name='subjects')
    op.drop_column('subjects', 'exam_type')
    op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    # ### end Alembic commands ###
