"""add original_code to subject

Revision ID: 0a636d9e6502
Revises: d0cef223d1e7
Create Date: 2025-12-20 19:47:51.654740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a636d9e6502'
down_revision: Union[str, Sequence[str], None] = 'd0cef223d1e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    #op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    op.add_column('subjects', sa.Column('original_code', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_subjects_original_code'), 'subjects', ['original_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subjects_original_code'), table_name='subjects')
    op.drop_column('subjects', 'original_code')
    op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    # ### end Alembic commands ###
