"""Add SubjectScoreValidationIssue model

Revision ID: c03b939618f6
Revises: f8c9d86daede
Create Date: 2025-12-26 11:44:13.549296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c03b939618f6'
down_revision: Union[str, Sequence[str], None] = 'f8c9d86daede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_score_validation_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_score_id', sa.Integer(), nullable=False),
    sa.Column('exam_subject_id', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.Enum('MISSING_SCORE', 'INVALID_SCORE', name='validationissuetype'), nullable=False),
    sa.Column('field_name', sa.String(length=20), nullable=False),
    sa.Column('test_type', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RESOLVED', 'IGNORED', name='validationissuestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_subject_id'], ['exam_subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_score_id'], ['subject_scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_score_validation_issues_exam_subject_id'), 'subject_score_validation_issues', ['exam_subject_id'], unique=False)
    op.create_index(op.f('ix_subject_score_validation_issues_issue_type'), 'subject_score_validation_issues', ['issue_type'], unique=False)
    op.create_index(op.f('ix_subject_score_validation_issues_status'), 'subject_score_validation_issues', ['status'], unique=False)
    op.create_index(op.f('ix_subject_score_validation_issues_subject_score_id'), 'subject_score_validation_issues', ['subject_score_id'], unique=False)
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.drop_index(op.f('ix_subject_score_validation_issues_subject_score_id'), table_name='subject_score_validation_issues')
    op.drop_index(op.f('ix_subject_score_validation_issues_status'), table_name='subject_score_validation_issues')
    op.drop_index(op.f('ix_subject_score_validation_issues_issue_type'), table_name='subject_score_validation_issues')
    op.drop_index(op.f('ix_subject_score_validation_issues_exam_subject_id'), table_name='subject_score_validation_issues')
    op.drop_table('subject_score_validation_issues')
    # ### end Alembic commands ###
