"""change use id to uuid

Revision ID: 407aea75c125
Revises: 8ecffc640e80
Create Date: 2025-12-31 01:23:25.446664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '407aea75c125'
down_revision: Union[str, Sequence[str], None] = '8ecffc640e80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if users table exists and if id column is INTEGER
    # If table was created with UUID in previous migration, this is a no-op
    # If table doesn't exist, this is also a no-op (first migration will create it with UUID)
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if 'users' not in inspector.get_table_names():
        # Table doesn't exist yet, first migration will create it with UUID
        # This is a no-op
        return

    # Table exists, check if we need to convert
    columns = {col['name']: col for col in inspector.get_columns('users')}
    if 'id' not in columns:
        # No id column, skip
        return

    id_type = str(columns['id']['type']).upper()
    if 'UUID' in id_type:
        # Already UUID, no-op
        return

    if 'INTEGER' in id_type:
        # Need to convert INTEGER to UUID
        # First, drop the primary key constraint
        op.drop_constraint('users_pkey', 'users', type_='primary')
        # Drop any default value on the column
        op.execute("ALTER TABLE users ALTER COLUMN id DROP DEFAULT")
        # Convert column type - generate new UUIDs for existing rows
        op.execute("ALTER TABLE users ALTER COLUMN id TYPE UUID USING gen_random_uuid()")
        # Set new default value for UUID
        op.execute("ALTER TABLE users ALTER COLUMN id SET DEFAULT gen_random_uuid()")
        # Re-add the primary key constraint
        op.create_primary_key('users_pkey', 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if users table exists and if id column is UUID
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if 'users' in inspector.get_table_names():
        columns = {col['name']: col for col in inspector.get_columns('users')}
        if 'id' in columns and 'UUID' in str(columns['id']['type']).upper():
            # Need to convert UUID to INTEGER
            # Note: This will lose data if there are existing UUIDs
            # Drop the primary key constraint
            op.drop_constraint('users_pkey', 'users', type_='primary')
            # Convert column type (this will generate new integer IDs)
            op.execute("ALTER TABLE users ALTER COLUMN id TYPE INTEGER USING (random() * 2147483647)::INTEGER")
            # Re-add primary key
            op.create_primary_key('users_pkey', 'users', ['id'])
    # ### end Alembic commands ###
