"""add pdfgerationjob model

Revision ID: 689ce90bd990
Revises: e0e8601a3da0
Create Date: 2025-12-22 21:09:15.904158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '689ce90bd990'
down_revision: Union[str, Sequence[str], None] = 'e0e8601a3da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_generation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='pdfgenerationjobstatus'), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('school_ids', sa.JSON(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('test_types', sa.JSON(), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('current_school_name', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdf_generation_jobs_created_at'), 'pdf_generation_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_pdf_generation_jobs_exam_id'), 'pdf_generation_jobs', ['exam_id'], unique=False)
    op.create_index(op.f('ix_pdf_generation_jobs_status'), 'pdf_generation_jobs', ['status'], unique=False)
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    # # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.drop_index(op.f('ix_pdf_generation_jobs_status'), table_name='pdf_generation_jobs')
    op.drop_index(op.f('ix_pdf_generation_jobs_exam_id'), table_name='pdf_generation_jobs')
    op.drop_index(op.f('ix_pdf_generation_jobs_created_at'), table_name='pdf_generation_jobs')
    op.drop_table('pdf_generation_jobs')
    # ### end Alembic commands ###
