"""Add unMatchedExtractionRecord model

Revision ID: 498707f3cb81
Revises: 29e48f44f608
Create Date: 2025-12-25 12:56:12.152440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '498707f3cb81'
down_revision: Union[str, Sequence[str], None] = '29e48f44f608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unmatched_extraction_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('index_number', sa.String(length=50), nullable=True),
    sa.Column('candidate_name', sa.String(length=255), nullable=True),
    sa.Column('score', sa.String(length=10), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RESOLVED', 'IGNORED', name='unmatchedrecordstatus'), nullable=False),
    #sa.Column('extraction_method', sa.Enum('AUTOMATED_EXTRACTION', 'MANUAL_TRANSCRIPTION_DIGITAL', 'MANUAL_ENTRY_PHYSICAL', name='dataextractionmethod'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unmatched_extraction_records_document_id'), 'unmatched_extraction_records', ['document_id'], unique=False)
    op.create_index(op.f('ix_unmatched_extraction_records_index_number'), 'unmatched_extraction_records', ['index_number'], unique=False)
    op.create_index(op.f('ix_unmatched_extraction_records_status'), 'unmatched_extraction_records', ['status'], unique=False)
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    # # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.drop_index(op.f('ix_unmatched_extraction_records_status'), table_name='unmatched_extraction_records')
    op.drop_index(op.f('ix_unmatched_extraction_records_index_number'), table_name='unmatched_extraction_records')
    op.drop_index(op.f('ix_unmatched_extraction_records_document_id'), table_name='unmatched_extraction_records')
    op.drop_table('unmatched_extraction_records')
    # ### end Alembic commands ###
