"""Fix enums

Revision ID: 44e83c96d408
Revises: 1a2b3c4d5e6f
Create Date: 2026-01-24 13:24:14.862190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '44e83c96d408'
down_revision: Union[str, Sequence[str], None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    op.sync_enum_values(
        enum_schema='public',
        enum_name='programmetype',
        new_values=['cert2', 'nvti'],
        affected_columns=[TableReference(table_schema='public', table_name='subjects', column_name='programme_type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='programmetype',
        new_values=['CERT2', 'NVTI'],
        affected_columns=[TableReference(table_schema='public', table_name='subjects', column_name='programme_type')],
        enum_values_to_rename=[],
    )
    # op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    # op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    # ### end Alembic commands ###
