"""Update subject model

Revision ID: 5b14bf70bd7c
Revises: 2dfc4acb25ce
Create Date: 2026-01-19 22:22:40.464434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b14bf70bd7c'
down_revision: Union[str, Sequence[str], None] = '2dfc4acb25ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('cert2', 'nvti', name='programmetype').create(op.get_bind())
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    op.add_column('subjects', sa.Column('programme_type', postgresql.ENUM('cert2', 'nvti', name='programmetype', create_type=False), nullable=True))
    op.alter_column('subjects', 'code',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=False)

    # Handle existing CBT exam_type values before updating enum
    # Convert CBT to CERTIFICATE_II (or handle as needed)
    connection = op.get_bind()
    # Check if CBT exists in the enum and if there are any records using it
    connection.execute(sa.text("""
        DO $$
        BEGIN
            -- If CBT exists in examtype enum, update all CBT records to CERTIFICATE_II
            IF EXISTS (
                SELECT 1 FROM pg_enum
                WHERE enumlabel = 'CBT'
                AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'examtype')
            ) THEN
                -- Update exams table
                UPDATE exams SET exam_type = 'CERTIFICATE_II' WHERE exam_type = 'CBT';
                -- Update programmes table
                UPDATE programmes SET exam_type = 'CERTIFICATE_II' WHERE exam_type = 'CBT';
                -- Update subjects table
                UPDATE subjects SET exam_type = 'CERTIFICATE_II' WHERE exam_type = 'CBT';
            END IF;
        END $$;
    """))

    op.sync_enum_values(
        enum_schema='public',
        enum_name='examtype',
        new_values=['CERTIFICATE_II', 'ADVANCE', 'TECHNICIAN_PART_I', 'TECHNICIAN_PART_II', 'TECHNICIAN_PART_III', 'DIPLOMA'],
        affected_columns=[TableReference(table_schema='public', table_name='exams', column_name='exam_type'), TableReference(table_schema='public', table_name='programmes', column_name='exam_type'), TableReference(table_schema='public', table_name='subjects', column_name='exam_type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='examtype',
        new_values=['CERTIFICATE_II', 'CBT'],
        affected_columns=[TableReference(table_schema='public', table_name='exams', column_name='exam_type'), TableReference(table_schema='public', table_name='programmes', column_name='exam_type'), TableReference(table_schema='public', table_name='subjects', column_name='exam_type')],
        enum_values_to_rename=[],
    )
    op.alter_column('subjects', 'code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
    op.drop_column('subjects', 'programme_type')
    # op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    # op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    sa.Enum('cert2', 'nvti', name='programmetype').drop(op.get_bind())
    # ### end Alembic commands ###
