services:
  traefik:
    image: traefik:v3.6
    container_name: registration-traefik
    command:
      - "--configfile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./traefik/certs:/certs:ro
      - traefik_certs:/certificates
      - traefik_logs:/var/log/traefik
    labels:
      - "traefik.enable=true"
      # Dashboard
      - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.service=api@internal"
    restart: unless-stopped
    networks:
      - registration-network
    depends_on:
      - registration-backend
      - registration-frontend

  registration-backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: registration-backend
    env_file:
      - .env.deploy
    environment:
      - ENVIRONMENT=production
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=80
    volumes:
      - registration_storage_data:/app/storage/documents
      - registration_photos_data:/app/storage/photos
      - registration_exports_data:/app/storage/exports
    command: >
      sh -c "
        if [ -f app/scripts/prestart.sh ]; then
          bash app/scripts/prestart.sh
        fi &&
        fastapi run app/main.py --port 80
      "
    restart: unless-stopped
    depends_on:
      registration_postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - registration-network
    labels:
      - "traefik.enable=true"
      # Backend service (must be defined before routers)
      - "traefik.http.services.backend.loadbalancer.server.port=80"
      # Backend API router - Domain-based
      - "traefik.http.routers.backend.rule=Host(`api.backend.localhost`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.service=backend"
      # Backend API router - HTTP (redirect to HTTPS)
      - "traefik.http.routers.backend-http.rule=Host(`api.backend.localhost`)"
      - "traefik.http.routers.backend-http.entrypoints=web"
      - "traefik.http.routers.backend-http.service=backend"

  registration-frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
      args:
        - NEXT_PUBLIC_API_BASE_URL=https://api.backend.localhost
    container_name: registration-frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=https://api.backend.localhost
    restart: unless-stopped
    depends_on:
      registration-backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --no-verbose --tries=1 http://127.0.0.1:3001/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - registration-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=3001"
      # Frontend router - HTTPS
      - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.service=frontend"
      # Frontend router - HTTP (redirect to HTTPS)
      - "traefik.http.routers.frontend-http.rule=Host(`frontend.localhost`)"
      - "traefik.http.routers.frontend-http.entrypoints=web"
      - "traefik.http.routers.frontend-http.service=frontend"

  registration_postgres:
    image: postgres:18
    container_name: registration-postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - registration_db_data:/var/lib/postgresql/data/pgdata
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro
    env_file:
      - .env.deploy
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${REGISTRATION_POSTGRES_DB:-registration_portal_db}
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - registration-network

  # Optional: Database administration (internal only, not exposed via Traefik)
  registration-pgadmin:
    image: dpage/pgadmin4
    container_name: registration-pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@localhost.dev
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - registration_postgres
    networks:
      - registration-network
    # Not exposed via Traefik - access directly if needed for debugging

volumes:
  registration_db_data:
    driver: local
  registration_storage_data:
    driver: local
  registration_photos_data:
    driver: local
  registration_exports_data:
    driver: local
  pgadmin_data:
    driver: local
  traefik_certs:
    driver: local
  traefik_logs:
    driver: local

networks:
  registration-network:
    driver: bridge
    name: registration-network
