"""Update school model

Revision ID: 00ec9f15168b
Revises: 1d174854e379
Create Date: 2026-01-16 00:55:27.954486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00ec9f15168b'
down_revision: Union[str, Sequence[str], None] = '1d174854e379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    op.add_column('schools', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('schools', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('schools', sa.Column('digital_address', sa.String(length=50), nullable=True))
    op.add_column('schools', sa.Column('post_office_address', sa.String(length=255), nullable=True))
    op.add_column('schools', sa.Column('is_private', sa.Boolean(), nullable=True))
    op.add_column('schools', sa.Column('principal_name', sa.String(length=255), nullable=True))
    op.add_column('schools', sa.Column('principal_email', sa.String(length=255), nullable=True))
    op.add_column('schools', sa.Column('principal_phone', sa.String(length=50), nullable=True))
    op.add_column('schools', sa.Column('profile_completed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_schools_profile_completed'), 'schools', ['profile_completed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schools_profile_completed'), table_name='schools')
    op.drop_column('schools', 'profile_completed')
    op.drop_column('schools', 'principal_phone')
    op.drop_column('schools', 'principal_email')
    op.drop_column('schools', 'principal_name')
    op.drop_column('schools', 'is_private')
    op.drop_column('schools', 'post_office_address')
    op.drop_column('schools', 'digital_address')
    op.drop_column('schools', 'phone')
    op.drop_column('schools', 'email')
    # op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    # op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    # # ### end Alembic commands ###
