"""Update examtype enum

Revision ID: 020ec4a481a2
Revises: 6d538e813189
Create Date: 2026-01-12 19:24:51.736368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '020ec4a481a2'
down_revision: Union[str, Sequence[str], None] = '6d538e813189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    op.alter_column('registration_exams', 'exam_series',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    #op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    op.alter_column('registration_exams', 'exam_series',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    #op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    # ### end Alembic commands ###
