"""Add tickets activities

Revision ID: 07bcd6cc6db5
Revises: db6f7283d80c
Create Date: 2026-01-06 15:00:05.898068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07bcd6cc6db5'
down_revision: Union[str, Sequence[str], None] = 'db6f7283d80c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('comment', 'status_change', 'assignment', 'note', 'system', name='ticketactivitytype').create(op.get_bind())
    sa.Enum('standard', 'express', name='servicetype').create(op.get_bind())
    sa.Enum('low', 'medium', 'high', 'urgent', name='ticketpriority').create(op.get_bind())
    op.create_table('ticket_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', postgresql.ENUM('comment', 'status_change', 'assignment', 'note', 'system', name='ticketactivitytype', create_type=False), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('old_assigned_to', sa.UUID(), nullable=True),
    sa.Column('new_assigned_to', sa.UUID(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['certificate_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_activities_activity_type'), 'ticket_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_ticket_activities_created_at'), 'ticket_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_ticket_activities_ticket_id'), 'ticket_activities', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_ticket_activities_user_id'), 'ticket_activities', ['user_id'], unique=False)
    op.create_table('ticket_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['certificate_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_status_history_changed_by_user_id'), 'ticket_status_history', ['changed_by_user_id'], unique=False)
    op.create_index(op.f('ix_ticket_status_history_created_at'), 'ticket_status_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_ticket_status_history_ticket_id'), 'ticket_status_history', ['ticket_id'], unique=False)
    op.add_column('certificate_requests', sa.Column('candidate_name', sa.String(length=255), nullable=True))
    op.add_column('certificate_requests', sa.Column('candidate_index_number', sa.String(length=50), nullable=True))
    op.add_column('certificate_requests', sa.Column('school_name', sa.String(length=255), nullable=True))
    op.add_column('certificate_requests', sa.Column('programme_name', sa.String(length=255), nullable=True))
    op.add_column('certificate_requests', sa.Column('completion_year', sa.Integer(), nullable=True))
    op.add_column('certificate_requests', sa.Column('certificate_file_path', sa.String(length=512), nullable=True))
    op.add_column('certificate_requests', sa.Column('candidate_photograph_file_path', sa.String(length=512), nullable=True))
    op.add_column('certificate_requests', sa.Column('request_details', sa.Text(), nullable=True))
    op.add_column('certificate_requests', sa.Column('assigned_to_user_id', sa.UUID(), nullable=True))
    op.add_column('certificate_requests', sa.Column('priority', postgresql.ENUM('low', 'medium', 'high', 'urgent', name='ticketpriority', create_type=False), nullable=False))
    op.add_column('certificate_requests', sa.Column('service_type', postgresql.ENUM('standard', 'express', name='servicetype', create_type=False), nullable=False))
    op.add_column('certificate_requests', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.add_column('certificate_requests', sa.Column('in_process_at', sa.DateTime(), nullable=True))
    op.add_column('certificate_requests', sa.Column('ready_for_dispatch_at', sa.DateTime(), nullable=True))
    op.add_column('certificate_requests', sa.Column('received_at', sa.DateTime(), nullable=True))
    op.add_column('certificate_requests', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.alter_column('certificate_requests', 'request_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('certificate', 'attestation', 'confirmation', 'verification', name='certificaterequesttype'),
               existing_nullable=False,
               postgresql_using='request_type::certificaterequesttype')
    op.alter_column('certificate_requests', 'examination_center_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('certificate_requests', 'national_id_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('certificate_requests', 'national_id_file_path',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('certificate_requests', 'photograph_file_path',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('certificate_requests', 'delivery_method',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('pickup', 'courier', name='deliverymethod'),
               nullable=True,
               postgresql_using='delivery_method::deliverymethod')
    op.alter_column('certificate_requests', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('pending_payment', 'paid', 'in_process', 'ready_for_dispatch', 'dispatched', 'received', 'completed', 'cancelled', name='requeststatus'),
               existing_nullable=False,
               postgresql_using='status::requeststatus')
    op.create_index(op.f('ix_certificate_requests_assigned_to_user_id'), 'certificate_requests', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_certificate_requests_candidate_index_number'), 'certificate_requests', ['candidate_index_number'], unique=False)
    op.create_index(op.f('ix_certificate_requests_completion_year'), 'certificate_requests', ['completion_year'], unique=False)
    op.create_index(op.f('ix_certificate_requests_priority'), 'certificate_requests', ['priority'], unique=False)
    op.create_index(op.f('ix_certificate_requests_service_type'), 'certificate_requests', ['service_type'], unique=False)
    op.create_foreign_key(None, 'certificate_requests', 'portal_users', ['assigned_to_user_id'], ['id'], ondelete='SET NULL')
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    op.sync_enum_values(
        enum_schema='public',
        enum_name='portalusertype',
        new_values=['SYSTEM_ADMIN', 'SCHOOL_ADMIN', 'SCHOOL_USER', 'PRIVATE_USER', 'ADMIN'],
        affected_columns=[TableReference(table_schema='public', table_name='portal_users', column_name='user_type')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='registrationstatus',
        new_values=['DRAFT', 'PENDING', 'APPROVED', 'REJECTED'],
        affected_columns=[TableReference(table_schema='public', table_name='registration_candidates', column_name='registration_status')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='certificaterequesttype',
        new_values=['certificate', 'attestation', 'confirmation', 'verification'],
        affected_columns=[TableReference(table_schema='public', table_name='certificate_requests', column_name='request_type')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='deliverymethod',
        new_values=['pickup', 'courier'],
        affected_columns=[TableReference(table_schema='public', table_name='certificate_requests', column_name='delivery_method')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='requeststatus',
        new_values=['pending_payment', 'paid', 'in_process', 'ready_for_dispatch', 'dispatched', 'received', 'completed', 'cancelled'],
        affected_columns=[TableReference(table_schema='public', table_name='certificate_requests', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='requeststatus',
        new_values=['PENDING_PAYMENT', 'PAID', 'IN_PROCESS', 'READY_FOR_DISPATCH', 'DISPATCHED', 'RECEIVED', 'COMPLETED', 'CANCELLED'],
        affected_columns=[TableReference(table_schema='public', table_name='certificate_requests', column_name='status')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='deliverymethod',
        new_values=['PICKUP', 'COURIER'],
        affected_columns=[TableReference(table_schema='public', table_name='certificate_requests', column_name='delivery_method')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='certificaterequesttype',
        new_values=['CERTIFICATE', 'ATTESTATION'],
        affected_columns=[TableReference(table_schema='public', table_name='certificate_requests', column_name='request_type')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='registrationstatus',
        new_values=['PENDING', 'APPROVED', 'REJECTED', 'DRAFT'],
        affected_columns=[TableReference(table_schema='public', table_name='registration_candidates', column_name='registration_status')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='portalusertype',
        new_values=['SYSTEM_ADMIN', 'SCHOOL_ADMIN', 'SCHOOL_USER', 'PRIVATE_USER'],
        affected_columns=[TableReference(table_schema='public', table_name='portal_users', column_name='user_type')],
        enum_values_to_rename=[],
    )
    # op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    # op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.drop_constraint(None, 'certificate_requests', type_='foreignkey')
    op.drop_index(op.f('ix_certificate_requests_service_type'), table_name='certificate_requests')
    op.drop_index(op.f('ix_certificate_requests_priority'), table_name='certificate_requests')
    op.drop_index(op.f('ix_certificate_requests_completion_year'), table_name='certificate_requests')
    op.drop_index(op.f('ix_certificate_requests_candidate_index_number'), table_name='certificate_requests')
    op.drop_index(op.f('ix_certificate_requests_assigned_to_user_id'), table_name='certificate_requests')
    op.alter_column('certificate_requests', 'status',
               existing_type=sa.Enum('pending_payment', 'paid', 'in_process', 'ready_for_dispatch', 'dispatched', 'received', 'completed', 'cancelled', name='requeststatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('certificate_requests', 'delivery_method',
               existing_type=sa.Enum('pickup', 'courier', name='deliverymethod'),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('certificate_requests', 'photograph_file_path',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('certificate_requests', 'national_id_file_path',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('certificate_requests', 'national_id_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('certificate_requests', 'examination_center_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('certificate_requests', 'request_type',
               existing_type=sa.Enum('certificate', 'attestation', 'confirmation', 'verification', name='certificaterequesttype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('certificate_requests', 'completed_at')
    op.drop_column('certificate_requests', 'received_at')
    op.drop_column('certificate_requests', 'ready_for_dispatch_at')
    op.drop_column('certificate_requests', 'in_process_at')
    op.drop_column('certificate_requests', 'paid_at')
    op.drop_column('certificate_requests', 'service_type')
    op.drop_column('certificate_requests', 'priority')
    op.drop_column('certificate_requests', 'assigned_to_user_id')
    op.drop_column('certificate_requests', 'request_details')
    op.drop_column('certificate_requests', 'candidate_photograph_file_path')
    op.drop_column('certificate_requests', 'certificate_file_path')
    op.drop_column('certificate_requests', 'completion_year')
    op.drop_column('certificate_requests', 'programme_name')
    op.drop_column('certificate_requests', 'school_name')
    op.drop_column('certificate_requests', 'candidate_index_number')
    op.drop_column('certificate_requests', 'candidate_name')
    op.drop_index(op.f('ix_ticket_status_history_ticket_id'), table_name='ticket_status_history')
    op.drop_index(op.f('ix_ticket_status_history_created_at'), table_name='ticket_status_history')
    op.drop_index(op.f('ix_ticket_status_history_changed_by_user_id'), table_name='ticket_status_history')
    op.drop_table('ticket_status_history')
    op.drop_index(op.f('ix_ticket_activities_user_id'), table_name='ticket_activities')
    op.drop_index(op.f('ix_ticket_activities_ticket_id'), table_name='ticket_activities')
    op.drop_index(op.f('ix_ticket_activities_created_at'), table_name='ticket_activities')
    op.drop_index(op.f('ix_ticket_activities_activity_type'), table_name='ticket_activities')
    op.drop_table('ticket_activities')
    sa.Enum('low', 'medium', 'high', 'urgent', name='ticketpriority').drop(op.get_bind())
    sa.Enum('standard', 'express', name='servicetype').drop(op.get_bind())
    sa.Enum('comment', 'status_change', 'assignment', 'note', 'system', name='ticketactivitytype').drop(op.get_bind())
    # ### end Alembic commands ###
