"""Modify addres column

Revision ID: 1d174854e379
Revises: 6c38864192d4
Create Date: 2026-01-14 20:08:57.952457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d174854e379'
down_revision: Union[str, Sequence[str], None] = '6c38864192d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    op.alter_column('registration_candidates', 'address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    #op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    op.alter_column('registration_candidates', 'address',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    #op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    # ### end Alembic commands ###
