"""Add index_number generation job model

Revision ID: 253c3e679d56
Revises: 2e69eaf6109f
Create Date: 2026-01-04 17:09:01.982515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '253c3e679d56'
down_revision: Union[str, Sequence[str], None] = '2e69eaf6109f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_number_generation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='indexnumbergenerationjobstatus'), nullable=False),
    sa.Column('replace_existing', sa.Boolean(), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('current_school_id', sa.Integer(), nullable=True),
    sa.Column('current_school_name', sa.String(length=255), nullable=True),
    sa.Column('school_progress', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exam_id'], ['registration_exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_index_number_generation_jobs_created_at'), 'index_number_generation_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_index_number_generation_jobs_created_by_user_id'), 'index_number_generation_jobs', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_index_number_generation_jobs_exam_id'), 'index_number_generation_jobs', ['exam_id'], unique=False)
    # op.create_index(op.f('ix_index_number_generation_jobs_status'), 'index_number_generation_jobs', ['status'], unique=False)
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    # op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.drop_index(op.f('ix_index_number_generation_jobs_status'), table_name='index_number_generation_jobs')
    op.drop_index(op.f('ix_index_number_generation_jobs_exam_id'), table_name='index_number_generation_jobs')
    op.drop_index(op.f('ix_index_number_generation_jobs_created_by_user_id'), table_name='index_number_generation_jobs')
    op.drop_index(op.f('ix_index_number_generation_jobs_created_at'), table_name='index_number_generation_jobs')
    op.drop_table('index_number_generation_jobs')
    # ### end Alembic commands ###
