"""Add user_id field to CertificateConfirmationRequest

Revision ID: 36b92ca6da04
Revises: 7faf235621e1
Create Date: 2026-01-06 22:33:02.935025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36b92ca6da04'
down_revision: Union[str, Sequence[str], None] = '7faf235621e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate_confirmation_requests', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_certificate_confirmation_requests_user_id'), 'certificate_confirmation_requests', ['user_id'], unique=False)
    op.create_foreign_key(None, 'certificate_confirmation_requests', 'portal_users', ['user_id'], ['id'], ondelete='SET NULL')
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    # # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    # op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.drop_constraint(None, 'certificate_confirmation_requests', type_='foreignkey')
    op.drop_index(op.f('ix_certificate_confirmation_requests_user_id'), table_name='certificate_confirmation_requests')
    op.drop_column('certificate_confirmation_requests', 'user_id')
    # ### end Alembic commands ###
