"""Add programme and subjects model

Revision ID: 46a1da573f2b
Revises: d5355974bdcb
Create Date: 2026-01-02 09:58:05.194838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46a1da573f2b'
down_revision: Union[str, Sequence[str], None] = 'd5355974bdcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programmes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programmes_code'), 'programmes', ['code'], unique=True)
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject_type', sa.Enum('CORE', 'ELECTIVE', name='subjecttype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=True)
    op.create_table('programme_subjects',
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('is_compulsory', sa.Boolean(), nullable=True, comment='True for compulsory core subjects, False for optional core subjects, NULL for electives'),
    sa.Column('choice_group_id', sa.Integer(), nullable=True, comment='Groups optional core subjects together. Subjects in the same group require selecting exactly one'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('programme_id', 'subject_id'),
    sa.UniqueConstraint('programme_id', 'subject_id', name='uq_programme_subject')
    )
    op.create_index(op.f('ix_programme_subjects_choice_group_id'), 'programme_subjects', ['choice_group_id'], unique=False)
    op.create_table('school_programmes',
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('school_id', 'programme_id'),
    sa.UniqueConstraint('school_id', 'programme_id', name='uq_school_programme')
    )
    op.create_table('registration_candidate_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_candidate_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registration_candidate_id'], ['registration_candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_candidate_photos_checksum'), 'registration_candidate_photos', ['checksum'], unique=False)
    op.create_index(op.f('ix_registration_candidate_photos_registration_candidate_id'), 'registration_candidate_photos', ['registration_candidate_id'], unique=True)
    op.add_column('registration_candidates', sa.Column('programme_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_registration_candidates_programme_id'), 'registration_candidates', ['programme_id'], unique=False)
    op.create_foreign_key(None, 'registration_candidates', 'programmes', ['programme_id'], ['id'], ondelete='SET NULL')
    op.add_column('registration_subject_selections', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_registration_subject_selections_subject_id'), 'registration_subject_selections', ['subject_id'], unique=False)
    op.create_foreign_key(None, 'registration_subject_selections', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registration_subject_selections', type_='foreignkey')
    op.drop_index(op.f('ix_registration_subject_selections_subject_id'), table_name='registration_subject_selections')
    op.drop_column('registration_subject_selections', 'subject_id')
    op.drop_constraint(None, 'registration_candidates', type_='foreignkey')
    op.drop_index(op.f('ix_registration_candidates_programme_id'), table_name='registration_candidates')
    op.drop_column('registration_candidates', 'programme_id')
    op.drop_index(op.f('ix_registration_candidate_photos_registration_candidate_id'), table_name='registration_candidate_photos')
    op.drop_index(op.f('ix_registration_candidate_photos_checksum'), table_name='registration_candidate_photos')
    op.drop_table('registration_candidate_photos')
    op.drop_table('school_programmes')
    op.drop_index(op.f('ix_programme_subjects_choice_group_id'), table_name='programme_subjects')
    op.drop_table('programme_subjects')
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_programmes_code'), table_name='programmes')
    op.drop_table('programmes')
    # ### end Alembic commands ###
