"""Update examiners application model

Revision ID: 475d1203c946
Revises: 7a1c06fb27a0
Create Date: 2026-01-23 00:10:55.900890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '475d1203c946'
down_revision: Union[str, Sequence[str], None] = '7a1c06fb27a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_examiner_application_processing_received_by_user_id'), table_name='examiner_application_processing')
    op.drop_constraint(op.f('examiner_application_processing_received_by_user_id_fkey'), 'examiner_application_processing', type_='foreignkey')
    op.drop_column('examiner_application_processing', 'rejected_signature')
    op.drop_column('examiner_application_processing', 'accepted_signature')
    op.drop_column('examiner_application_processing', 'received_by_user_id')
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    # op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.add_column('examiner_application_processing', sa.Column('received_by_user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('examiner_application_processing', sa.Column('accepted_signature', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('examiner_application_processing', sa.Column('rejected_signature', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('examiner_application_processing_received_by_user_id_fkey'), 'examiner_application_processing', 'portal_users', ['received_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_examiner_application_processing_received_by_user_id'), 'examiner_application_processing', ['received_by_user_id'], unique=False)
    # ### end Alembic commands ###
