"""Add cert confirmation models

Revision ID: 48839b242ed1
Revises: 07bcd6cc6db5
Create Date: 2026-01-06 18:02:17.608019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48839b242ed1'
down_revision: Union[str, Sequence[str], None] = '07bcd6cc6db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_certificate_confirmations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bulk_request_number', sa.String(length=50), nullable=False),
    sa.Column('request_type', postgresql.ENUM('certificate', 'attestation', 'confirmation', 'verification', name='certificaterequesttype', create_type=False), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('service_type', postgresql.ENUM('standard', 'express', name='servicetype', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('pending_payment', 'paid', 'in_process', 'ready_for_dispatch', 'dispatched', 'received', 'completed', 'cancelled', name='requeststatus', create_type=False), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pdf_file_path', sa.String(length=512), nullable=True),
    sa.Column('pdf_generated_at', sa.DateTime(), nullable=True),
    sa.Column('pdf_generated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_user_id', sa.UUID(), nullable=True),
    sa.Column('priority', postgresql.ENUM('low', 'medium', 'high', 'urgent', name='ticketpriority', create_type=False), nullable=False),
    sa.Column('processed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('dispatched_by_user_id', sa.UUID(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('in_process_at', sa.DateTime(), nullable=True),
    sa.Column('ready_for_dispatch_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dispatched_by_user_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pdf_generated_by_user_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['processed_by_user_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_certificate_confirmations_assigned_to_user_id'), 'bulk_certificate_confirmations', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_bulk_certificate_confirmations_bulk_request_number'), 'bulk_certificate_confirmations', ['bulk_request_number'], unique=True)
    op.create_index(op.f('ix_bulk_certificate_confirmations_created_at'), 'bulk_certificate_confirmations', ['created_at'], unique=False)
    op.create_index(op.f('ix_bulk_certificate_confirmations_dispatched_by_user_id'), 'bulk_certificate_confirmations', ['dispatched_by_user_id'], unique=False)
    op.create_index(op.f('ix_bulk_certificate_confirmations_invoice_id'), 'bulk_certificate_confirmations', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_bulk_certificate_confirmations_payment_id'), 'bulk_certificate_confirmations', ['payment_id'], unique=False)
    op.create_index(op.f('ix_bulk_certificate_confirmations_pdf_generated_by_user_id'), 'bulk_certificate_confirmations', ['pdf_generated_by_user_id'], unique=False)
    op.create_index(op.f('ix_bulk_certificate_confirmations_priority'), 'bulk_certificate_confirmations', ['priority'], unique=False)
    op.create_index(op.f('ix_bulk_certificate_confirmations_processed_by_user_id'), 'bulk_certificate_confirmations', ['processed_by_user_id'], unique=False)
    op.create_index(op.f('ix_bulk_certificate_confirmations_request_type'), 'bulk_certificate_confirmations', ['request_type'], unique=False)
    op.create_index(op.f('ix_bulk_certificate_confirmations_service_type'), 'bulk_certificate_confirmations', ['service_type'], unique=False)
    op.create_index(op.f('ix_bulk_certificate_confirmations_status'), 'bulk_certificate_confirmations', ['status'], unique=False)
    op.create_table('certificate_confirmation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_number', sa.String(length=50), nullable=False),
    sa.Column('bulk_certificate_confirmation_id', sa.Integer(), nullable=True),
    sa.Column('request_type', postgresql.ENUM('certificate', 'attestation', 'confirmation', 'verification', name='certificaterequesttype', create_type=False), nullable=False),
    sa.Column('candidate_name', sa.String(length=255), nullable=False),
    sa.Column('candidate_index_number', sa.String(length=50), nullable=True),
    sa.Column('school_name', sa.String(length=255), nullable=False),
    sa.Column('programme_name', sa.String(length=255), nullable=False),
    sa.Column('completion_year', sa.Integer(), nullable=False),
    sa.Column('certificate_file_path', sa.String(length=512), nullable=True),
    sa.Column('candidate_photograph_file_path', sa.String(length=512), nullable=True),
    sa.Column('request_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bulk_certificate_confirmation_id'], ['bulk_certificate_confirmations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificate_confirmation_requests_bulk_certificate_confirmation_id'), 'certificate_confirmation_requests', ['bulk_certificate_confirmation_id'], unique=False)
    op.create_index(op.f('ix_certificate_confirmation_requests_candidate_index_number'), 'certificate_confirmation_requests', ['candidate_index_number'], unique=False)
    op.create_index(op.f('ix_certificate_confirmation_requests_completion_year'), 'certificate_confirmation_requests', ['completion_year'], unique=False)
    op.create_index(op.f('ix_certificate_confirmation_requests_request_number'), 'certificate_confirmation_requests', ['request_number'], unique=True)
    op.create_index(op.f('ix_certificate_confirmation_requests_request_type'), 'certificate_confirmation_requests', ['request_type'], unique=False)
    op.create_table('bulk_confirmation_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bulk_confirmation_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', postgresql.ENUM('comment', 'status_change', 'assignment', 'note', 'system', name='ticketactivitytype', create_type=False), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('old_assigned_to', sa.UUID(), nullable=True),
    sa.Column('new_assigned_to', sa.UUID(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bulk_confirmation_id'], ['bulk_certificate_confirmations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_confirmation_activities_activity_type'), 'bulk_confirmation_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_bulk_confirmation_activities_bulk_confirmation_id'), 'bulk_confirmation_activities', ['bulk_confirmation_id'], unique=False)
    op.create_index(op.f('ix_bulk_confirmation_activities_created_at'), 'bulk_confirmation_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_bulk_confirmation_activities_user_id'), 'bulk_confirmation_activities', ['user_id'], unique=False)
    op.create_table('bulk_confirmation_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bulk_confirmation_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bulk_confirmation_id'], ['bulk_certificate_confirmations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_confirmation_status_history_bulk_confirmation_id'), 'bulk_confirmation_status_history', ['bulk_confirmation_id'], unique=False)
    op.create_index(op.f('ix_bulk_confirmation_status_history_changed_by_user_id'), 'bulk_confirmation_status_history', ['changed_by_user_id'], unique=False)
    op.create_index(op.f('ix_bulk_confirmation_status_history_created_at'), 'bulk_confirmation_status_history', ['created_at'], unique=False)
    op.add_column('invoices', sa.Column('bulk_certificate_confirmation_id', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('certificate_confirmation_request_id', sa.Integer(), nullable=True))
    op.alter_column('invoices', 'certificate_request_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_invoices_bulk_certificate_confirmation_id'), 'invoices', ['bulk_certificate_confirmation_id'], unique=True)
    op.create_index(op.f('ix_invoices_certificate_confirmation_request_id'), 'invoices', ['certificate_confirmation_request_id'], unique=True)
    op.create_foreign_key(None, 'invoices', 'bulk_certificate_confirmations', ['bulk_certificate_confirmation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'invoices', 'certificate_confirmation_requests', ['certificate_confirmation_request_id'], ['id'], ondelete='CASCADE')
    op.add_column('payments', sa.Column('bulk_certificate_confirmation_id', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('certificate_confirmation_request_id', sa.Integer(), nullable=True))
    op.alter_column('payments', 'certificate_request_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_payments_bulk_certificate_confirmation_id'), 'payments', ['bulk_certificate_confirmation_id'], unique=False)
    op.create_index(op.f('ix_payments_certificate_confirmation_request_id'), 'payments', ['certificate_confirmation_request_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'certificate_confirmation_requests', ['certificate_confirmation_request_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'payments', 'bulk_certificate_confirmations', ['bulk_certificate_confirmation_id'], ['id'], ondelete='CASCADE')
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    # # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    # op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_certificate_confirmation_request_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_bulk_certificate_confirmation_id'), table_name='payments')
    op.alter_column('payments', 'certificate_request_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('payments', 'certificate_confirmation_request_id')
    op.drop_column('payments', 'bulk_certificate_confirmation_id')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_certificate_confirmation_request_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_bulk_certificate_confirmation_id'), table_name='invoices')
    op.alter_column('invoices', 'certificate_request_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('invoices', 'certificate_confirmation_request_id')
    op.drop_column('invoices', 'bulk_certificate_confirmation_id')
    op.drop_index(op.f('ix_bulk_confirmation_status_history_created_at'), table_name='bulk_confirmation_status_history')
    op.drop_index(op.f('ix_bulk_confirmation_status_history_changed_by_user_id'), table_name='bulk_confirmation_status_history')
    op.drop_index(op.f('ix_bulk_confirmation_status_history_bulk_confirmation_id'), table_name='bulk_confirmation_status_history')
    op.drop_table('bulk_confirmation_status_history')
    op.drop_index(op.f('ix_bulk_confirmation_activities_user_id'), table_name='bulk_confirmation_activities')
    op.drop_index(op.f('ix_bulk_confirmation_activities_created_at'), table_name='bulk_confirmation_activities')
    op.drop_index(op.f('ix_bulk_confirmation_activities_bulk_confirmation_id'), table_name='bulk_confirmation_activities')
    op.drop_index(op.f('ix_bulk_confirmation_activities_activity_type'), table_name='bulk_confirmation_activities')
    op.drop_table('bulk_confirmation_activities')
    op.drop_index(op.f('ix_certificate_confirmation_requests_request_type'), table_name='certificate_confirmation_requests')
    op.drop_index(op.f('ix_certificate_confirmation_requests_request_number'), table_name='certificate_confirmation_requests')
    op.drop_index(op.f('ix_certificate_confirmation_requests_completion_year'), table_name='certificate_confirmation_requests')
    op.drop_index(op.f('ix_certificate_confirmation_requests_candidate_index_number'), table_name='certificate_confirmation_requests')
    op.drop_index(op.f('ix_certificate_confirmation_requests_bulk_certificate_confirmation_id'), table_name='certificate_confirmation_requests')
    op.drop_table('certificate_confirmation_requests')
    op.drop_index(op.f('ix_bulk_certificate_confirmations_status'), table_name='bulk_certificate_confirmations')
    op.drop_index(op.f('ix_bulk_certificate_confirmations_service_type'), table_name='bulk_certificate_confirmations')
    op.drop_index(op.f('ix_bulk_certificate_confirmations_request_type'), table_name='bulk_certificate_confirmations')
    op.drop_index(op.f('ix_bulk_certificate_confirmations_processed_by_user_id'), table_name='bulk_certificate_confirmations')
    op.drop_index(op.f('ix_bulk_certificate_confirmations_priority'), table_name='bulk_certificate_confirmations')
    op.drop_index(op.f('ix_bulk_certificate_confirmations_pdf_generated_by_user_id'), table_name='bulk_certificate_confirmations')
    op.drop_index(op.f('ix_bulk_certificate_confirmations_payment_id'), table_name='bulk_certificate_confirmations')
    op.drop_index(op.f('ix_bulk_certificate_confirmations_invoice_id'), table_name='bulk_certificate_confirmations')
    op.drop_index(op.f('ix_bulk_certificate_confirmations_dispatched_by_user_id'), table_name='bulk_certificate_confirmations')
    op.drop_index(op.f('ix_bulk_certificate_confirmations_created_at'), table_name='bulk_certificate_confirmations')
    op.drop_index(op.f('ix_bulk_certificate_confirmations_bulk_request_number'), table_name='bulk_certificate_confirmations')
    op.drop_index(op.f('ix_bulk_certificate_confirmations_assigned_to_user_id'), table_name='bulk_certificate_confirmations')
    op.drop_table('bulk_certificate_confirmations')
    # ### end Alembic commands ###
