"""Add photo validation job model

Revision ID: 4d43320db193
Revises: 745eb6f2d0a3
Create Date: 2026-01-18 01:18:18.343742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d43320db193'
down_revision: Union[str, Sequence[str], None] = '745eb6f2d0a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='photovalidationjobstatus').create(op.get_bind())
    op.create_table('photo_validation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='photovalidationjobstatus', create_type=False), nullable=False),
    sa.Column('validation_level', sa.String(length=20), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('total_photos', sa.Integer(), nullable=False),
    sa.Column('valid_count', sa.Integer(), nullable=False),
    sa.Column('invalid_count', sa.Integer(), nullable=False),
    sa.Column('result_zip_path', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_validation_jobs_created_at'), 'photo_validation_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_photo_validation_jobs_created_by_user_id'), 'photo_validation_jobs', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_photo_validation_jobs_school_id'), 'photo_validation_jobs', ['school_id'], unique=False)
    op.create_index(op.f('ix_photo_validation_jobs_status'), 'photo_validation_jobs', ['status'], unique=False)
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    # op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.drop_index(op.f('ix_photo_validation_jobs_status'), table_name='photo_validation_jobs')
    op.drop_index(op.f('ix_photo_validation_jobs_school_id'), table_name='photo_validation_jobs')
    op.drop_index(op.f('ix_photo_validation_jobs_created_by_user_id'), table_name='photo_validation_jobs')
    op.drop_index(op.f('ix_photo_validation_jobs_created_at'), table_name='photo_validation_jobs')
    op.drop_table('photo_validation_jobs')
    sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='photovalidationjobstatus').drop(op.get_bind())
    # ### end Alembic commands ###
