"""Update exam schedule model

Revision ID: 52de03ff3bed
Revises: ecc45d517eff
Create Date: 2026-01-11 23:53:37.827542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52de03ff3bed'
down_revision: Union[str, Sequence[str], None] = 'ecc45d517eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add papers column with default value for backward compatibility
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name='examination_schedules'
                AND column_name='papers'
            ) THEN
                ALTER TABLE examination_schedules
                ADD COLUMN papers JSONB NOT NULL DEFAULT '[{"paper": 1}]'::jsonb;
            END IF;
        END $$;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    # op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.drop_column('examination_schedules', 'papers')
    # ### end Alembic commands ###
