"""Add ExamPricing model

Revision ID: 6c38864192d4
Revises: ff260e8a59e9
Create Date: 2026-01-13 19:40:31.183102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c38864192d4'
down_revision: Union[str, Sequence[str], None] = 'ff260e8a59e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_pricing_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('registration_type', postgresql.ENUM('free_tvet', 'private', 'referral', name='registrationtype', create_type=False), nullable=True),
    sa.Column('pricing_model_preference', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['registration_exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'registration_type', name='uq_exam_pricing_model')
    )
    op.create_index(op.f('ix_exam_pricing_models_exam_id'), 'exam_pricing_models', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_pricing_models_registration_type'), 'exam_pricing_models', ['registration_type'], unique=False)
    #op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    #op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    #op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.drop_index(op.f('ix_exam_pricing_models_registration_type'), table_name='exam_pricing_models')
    op.drop_index(op.f('ix_exam_pricing_models_exam_id'), table_name='exam_pricing_models')
    op.drop_table('exam_pricing_models')
    # ### end Alembic commands ###
