"""add api keys and credit system

Revision ID: 6d538e813189
Revises: 76e7f536fbfb
Create Date: 2026-01-12 12:42:48.861024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d538e813189'
down_revision: Union[str, Sequence[str], None] = '76e7f536fbfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('single', 'bulk', name='apirequesttype').create(op.get_bind())
    sa.Enum('api_key', 'dashboard', name='apirequestsource').create(op.get_bind())
    sa.Enum('purchase', 'admin_assignment', 'usage', 'refund', name='credittransactiontype').create(op.get_bind())
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('request_count_reset_at', sa.DateTime(), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('total_verifications', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['portal_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=False)
    op.create_index(op.f('ix_api_keys_last_used_at'), 'api_keys', ['last_used_at'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('user_credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_purchased', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_used', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['portal_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_credits_user_id'), 'user_credits', ['user_id'], unique=True)
    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('request_source', postgresql.ENUM('api_key', 'dashboard', name='apirequestsource', create_type=False), nullable=False),
    sa.Column('request_type', postgresql.ENUM('single', 'bulk', name='apirequesttype', create_type=False), nullable=False),
    sa.Column('verification_count', sa.Integer(), nullable=False),
    sa.Column('request_timestamp', sa.DateTime(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['portal_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_usage_api_key_id'), 'api_usage', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_api_usage_created_at'), 'api_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_usage_request_source'), 'api_usage', ['request_source'], unique=False)
    op.create_index(op.f('ix_api_usage_request_timestamp'), 'api_usage', ['request_timestamp'], unique=False)
    op.create_index(op.f('ix_api_usage_request_type'), 'api_usage', ['request_type'], unique=False)
    op.create_index(op.f('ix_api_usage_user_id'), 'api_usage', ['user_id'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_credit_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', postgresql.ENUM('purchase', 'admin_assignment', 'usage', 'refund', name='credittransactiontype', create_type=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by_user_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_credit_id'], ['user_credits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['portal_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_assigned_by_user_id'), 'credit_transactions', ['assigned_by_user_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_created_at'), 'credit_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_credit_transactions_payment_id'), 'credit_transactions', ['payment_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_transaction_type'), 'credit_transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_credit_transactions_user_credit_id'), 'credit_transactions', ['user_credit_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_user_id'), 'credit_transactions', ['user_id'], unique=False)
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    op.sync_enum_values(
        enum_schema='public',
        enum_name='role',
        new_values=['SystemAdmin', 'Director', 'DeputyDirector', 'PrincipalManager', 'SeniorManager', 'Manager', 'Staff', 'SchoolAdmin', 'SchoolStaff', 'PublicUser', 'APIUSER'],
        affected_columns=[TableReference(table_schema='public', table_name='portal_users', column_name='role'), TableReference(table_schema='public', table_name='role_permissions', column_name='role')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='role',
        new_values=['SystemAdmin', 'Director', 'DeputyDirector', 'PrincipalManager', 'SeniorManager', 'Manager', 'Staff', 'SchoolAdmin', 'SchoolStaff', 'PublicUser'],
        affected_columns=[TableReference(table_schema='public', table_name='portal_users', column_name='role'), TableReference(table_schema='public', table_name='role_permissions', column_name='role')],
        enum_values_to_rename=[],
    )
    # op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    # op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.drop_index(op.f('ix_credit_transactions_user_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_user_credit_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_transaction_type'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_payment_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_created_at'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_assigned_by_user_id'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_api_usage_user_id'), table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_request_type'), table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_request_timestamp'), table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_request_source'), table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_created_at'), table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_api_key_id'), table_name='api_usage')
    op.drop_table('api_usage')
    op.drop_index(op.f('ix_user_credits_user_id'), table_name='user_credits')
    op.drop_table('user_credits')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_last_used_at'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_table('api_keys')
    sa.Enum('purchase', 'admin_assignment', 'usage', 'refund', name='credittransactiontype').drop(op.get_bind())
    sa.Enum('api_key', 'dashboard', name='apirequestsource').drop(op.get_bind())
    sa.Enum('single', 'bulk', name='apirequesttype').drop(op.get_bind())
    # ### end Alembic commands ###
