"""Update examination schedule

Revision ID: 745eb6f2d0a3
Revises: 00ec9f15168b
Create Date: 2026-01-17 15:37:21.623856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '745eb6f2d0a3'
down_revision: Union[str, Sequence[str], None] = '00ec9f15168b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('examination_schedules', 'examination_time')
    op.drop_column('examination_schedules', 'examination_end_time')
    op.drop_column('examination_schedules', 'examination_date')
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    # # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    # op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.add_column('examination_schedules', sa.Column('examination_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('examination_schedules', sa.Column('examination_end_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('examination_schedules', sa.Column('examination_time', postgresql.TIME(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
