"""TicketActivity models

Revision ID: 7710c726e0bb
Revises: db6f7283d80c
Create Date: 2026-01-05 18:40:27.008529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '7710c726e0bb'
down_revision: Union[str, Sequence[str], None] = 'db6f7283d80c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop tables that might use the enums first (from previous failed migrations)
    op.execute("DROP TABLE IF EXISTS ticket_activities CASCADE")
    op.execute("DROP TABLE IF EXISTS ticket_status_history CASCADE")

    # Drop old enum types if they exist (they were created but never used, columns are still VARCHAR)
    # This is safe because the columns are VARCHAR, not using these enums
    # Also drop new enum types if they exist from a previous failed migration
    op.execute("DROP TYPE IF EXISTS certificaterequesttype CASCADE")
    op.execute("DROP TYPE IF EXISTS deliverymethod CASCADE")
    op.execute("DROP TYPE IF EXISTS requeststatus CASCADE")
    op.execute("DROP TYPE IF EXISTS ticketactivitytype CASCADE")
    op.execute("DROP TYPE IF EXISTS ticketpriority CASCADE")
    op.execute("DROP TYPE IF EXISTS servicetype CASCADE")

    # Convert existing data to lowercase before creating new enums
    # This ensures data matches the new enum values
    op.execute("""
        UPDATE certificate_requests
        SET request_type = LOWER(request_type),
            delivery_method = LOWER(delivery_method),
            status = LOWER(status)
        WHERE request_type IS NOT NULL OR delivery_method IS NOT NULL OR status IS NOT NULL;
    """)

    # Create enum types with lowercase values (matching models)
    # Use EXCEPTION handling for idempotent enum creation
    # Create ticketpriority enum
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE ticketpriority AS ENUM ('low', 'medium', 'high', 'urgent');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)

    # Create servicetype enum
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE servicetype AS ENUM ('standard', 'express');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)

    # Create ticketactivitytype enum
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE ticketactivitytype AS ENUM ('comment', 'status_change', 'assignment', 'note', 'system');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)

    # Create certificaterequesttype enum
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE certificaterequesttype AS ENUM ('certificate', 'attestation');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)

    # Create deliverymethod enum
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE deliverymethod AS ENUM ('pickup', 'courier');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)

    # Create requeststatus enum
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE requeststatus AS ENUM ('pending_payment', 'paid', 'in_process', 'ready_for_dispatch', 'dispatched', 'received', 'completed', 'cancelled');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.Enum('comment', 'status_change', 'assignment', 'note', 'system', name='ticketactivitytype', create_type=False), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('old_assigned_to', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('new_assigned_to', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['certificate_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_activities_activity_type'), 'ticket_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_ticket_activities_created_at'), 'ticket_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_ticket_activities_ticket_id'), 'ticket_activities', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_ticket_activities_user_id'), 'ticket_activities', ['user_id'], unique=False)
    op.create_table('ticket_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by_user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['certificate_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_status_history_changed_by_user_id'), 'ticket_status_history', ['changed_by_user_id'], unique=False)
    op.create_index(op.f('ix_ticket_status_history_created_at'), 'ticket_status_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_ticket_status_history_ticket_id'), 'ticket_status_history', ['ticket_id'], unique=False)
    op.add_column('certificate_requests', sa.Column('assigned_to_user_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('certificate_requests', sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='ticketpriority', create_type=False), nullable=False, server_default='medium'))
    op.add_column('certificate_requests', sa.Column('service_type', sa.Enum('standard', 'express', name='servicetype', create_type=False), nullable=False, server_default='standard'))
    op.add_column('certificate_requests', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.add_column('certificate_requests', sa.Column('in_process_at', sa.DateTime(), nullable=True))
    op.add_column('certificate_requests', sa.Column('ready_for_dispatch_at', sa.DateTime(), nullable=True))
    op.add_column('certificate_requests', sa.Column('received_at', sa.DateTime(), nullable=True))
    op.add_column('certificate_requests', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # Alter columns with explicit USING clauses to cast VARCHAR to enum types
    # First convert to VARCHAR if it's already an enum, then to the new enum type
    # This handles the case where the old enum type still exists
    op.execute("""
        DO $$
        BEGIN
            -- Check if column is already an enum type, convert to VARCHAR first
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'certificate_requests'
                AND column_name = 'request_type'
                AND udt_name IN ('certificaterequesttype', 'varchar')
            ) THEN
                -- If it's an enum, convert to VARCHAR first
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'certificate_requests'
                    AND column_name = 'request_type'
                    AND udt_name = 'certificaterequesttype'
                ) THEN
                    ALTER TABLE certificate_requests
                    ALTER COLUMN request_type TYPE VARCHAR(50)
                    USING request_type::text;
                END IF;
            END IF;
        END $$;
    """)

    op.execute("""
        ALTER TABLE certificate_requests
        ALTER COLUMN request_type
        TYPE certificaterequesttype
        USING LOWER(request_type)::certificaterequesttype;
    """)

    op.execute("""
        DO $$
        BEGIN
            -- Check if column is already an enum type, convert to VARCHAR first
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'certificate_requests'
                AND column_name = 'delivery_method'
                AND udt_name = 'deliverymethod'
            ) THEN
                ALTER TABLE certificate_requests
                ALTER COLUMN delivery_method TYPE VARCHAR(50)
                USING delivery_method::text;
            END IF;
        END $$;
    """)

    op.execute("""
        ALTER TABLE certificate_requests
        ALTER COLUMN delivery_method
        TYPE deliverymethod
        USING LOWER(delivery_method)::deliverymethod;
    """)

    op.execute("""
        DO $$
        BEGIN
            -- Check if column is already an enum type, convert to VARCHAR first
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'certificate_requests'
                AND column_name = 'status'
                AND udt_name = 'requeststatus'
            ) THEN
                ALTER TABLE certificate_requests
                ALTER COLUMN status TYPE VARCHAR(50)
                USING status::text;
            END IF;
        END $$;
    """)

    op.execute("""
        ALTER TABLE certificate_requests
        ALTER COLUMN status
        TYPE requeststatus
        USING LOWER(status)::requeststatus;
    """)
    op.create_index(op.f('ix_certificate_requests_assigned_to_user_id'), 'certificate_requests', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_certificate_requests_priority'), 'certificate_requests', ['priority'], unique=False)
    op.create_index(op.f('ix_certificate_requests_service_type'), 'certificate_requests', ['service_type'], unique=False)
    op.create_foreign_key(None, 'certificate_requests', 'portal_users', ['assigned_to_user_id'], ['id'], ondelete='SET NULL')

    # Backfill status timestamps from existing data where possible
    # Set paid_at for requests with status PAID or later
    op.execute("""
        UPDATE certificate_requests
        SET paid_at = updated_at
        WHERE status IN ('paid', 'in_process', 'ready_for_dispatch', 'dispatched', 'received', 'completed')
        AND paid_at IS NULL;
    """)

    # Set in_process_at for requests with status IN_PROCESS or later
    op.execute("""
        UPDATE certificate_requests
        SET in_process_at = updated_at
        WHERE status IN ('in_process', 'ready_for_dispatch', 'dispatched', 'received', 'completed')
        AND in_process_at IS NULL;
    """)

    # Set ready_for_dispatch_at for requests with status READY_FOR_DISPATCH or later
    op.execute("""
        UPDATE certificate_requests
        SET ready_for_dispatch_at = updated_at
        WHERE status IN ('ready_for_dispatch', 'dispatched', 'received', 'completed')
        AND ready_for_dispatch_at IS NULL;
    """)

    # Set received_at for requests with status RECEIVED or later
    op.execute("""
        UPDATE certificate_requests
        SET received_at = updated_at
        WHERE status IN ('received', 'completed')
        AND received_at IS NULL;
    """)

    # Set completed_at for requests with status COMPLETED
    op.execute("""
        UPDATE certificate_requests
        SET completed_at = updated_at
        WHERE status = 'completed'
        AND completed_at IS NULL;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    # op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.drop_constraint(None, 'certificate_requests', type_='foreignkey')
    op.drop_index(op.f('ix_certificate_requests_service_type'), table_name='certificate_requests')
    op.drop_index(op.f('ix_certificate_requests_priority'), table_name='certificate_requests')
    op.drop_index(op.f('ix_certificate_requests_assigned_to_user_id'), table_name='certificate_requests')
    op.alter_column('certificate_requests', 'status',
               existing_type=sa.Enum('pending_payment', 'paid', 'in_process', 'ready_for_dispatch', 'dispatched', 'received', 'completed', 'cancelled', name='requeststatus', create_type=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('certificate_requests', 'delivery_method',
               existing_type=sa.Enum('pickup', 'courier', name='deliverymethod', create_type=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('certificate_requests', 'request_type',
               existing_type=sa.Enum('certificate', 'attestation', name='certificaterequesttype', create_type=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('certificate_requests', 'completed_at')
    op.drop_column('certificate_requests', 'received_at')
    op.drop_column('certificate_requests', 'ready_for_dispatch_at')
    op.drop_column('certificate_requests', 'in_process_at')
    op.drop_column('certificate_requests', 'paid_at')
    op.drop_column('certificate_requests', 'service_type')
    op.drop_column('certificate_requests', 'priority')
    op.drop_column('certificate_requests', 'assigned_to_user_id')
    op.drop_index(op.f('ix_ticket_status_history_ticket_id'), table_name='ticket_status_history')
    op.drop_index(op.f('ix_ticket_status_history_created_at'), table_name='ticket_status_history')
    op.drop_index(op.f('ix_ticket_status_history_changed_by_user_id'), table_name='ticket_status_history')
    op.drop_table('ticket_status_history')
    op.drop_index(op.f('ix_ticket_activities_user_id'), table_name='ticket_activities')
    op.drop_index(op.f('ix_ticket_activities_ticket_id'), table_name='ticket_activities')
    op.drop_index(op.f('ix_ticket_activities_created_at'), table_name='ticket_activities')
    op.drop_index(op.f('ix_ticket_activities_activity_type'), table_name='ticket_activities')
    op.drop_table('ticket_activities')

    # Drop enum types
    op.execute("DROP TYPE IF EXISTS ticketactivitytype CASCADE")
    op.execute("DROP TYPE IF EXISTS servicetype CASCADE")
    op.execute("DROP TYPE IF EXISTS ticketpriority CASCADE")
    op.execute("DROP TYPE IF EXISTS requeststatus CASCADE")
    op.execute("DROP TYPE IF EXISTS deliverymethod CASCADE")
    op.execute("DROP TYPE IF EXISTS certificaterequesttype CASCADE")
    # ### end Alembic commands ###
