"""Add programme pricing

Revision ID: 796c30db4172
Revises: update_reg_type_enum
Create Date: 2026-01-13 18:27:29.031877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '796c30db4172'
down_revision: Union[str, Sequence[str], None] = 'update_reg_type_enum'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programme_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['registration_exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('programme_id', 'exam_id', name='uq_programme_pricing')
    )
    op.create_index(op.f('ix_programme_pricing_exam_id'), 'programme_pricing', ['exam_id'], unique=False)
    op.create_index(op.f('ix_programme_pricing_is_active'), 'programme_pricing', ['is_active'], unique=False)
    op.create_index(op.f('ix_programme_pricing_programme_id'), 'programme_pricing', ['programme_id'], unique=False)
   # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    #op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    #op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.drop_index(op.f('ix_programme_pricing_programme_id'), table_name='programme_pricing')
    op.drop_index(op.f('ix_programme_pricing_is_active'), table_name='programme_pricing')
    op.drop_index(op.f('ix_programme_pricing_exam_id'), table_name='programme_pricing')
    op.drop_table('programme_pricing')
    # ### end Alembic commands ###
