"""Update Cert confirmation and request models

Revision ID: 7faf235621e1
Revises: 48839b242ed1
Create Date: 2026-01-06 21:46:51.653213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7faf235621e1'
down_revision: Union[str, Sequence[str], None] = '48839b242ed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop dependent tables first (they have foreign keys to bulk_certificate_confirmations)
    op.drop_index(op.f('ix_bulk_confirmation_status_history_bulk_confirmation_id'), table_name='bulk_confirmation_status_history')
    op.drop_index(op.f('ix_bulk_confirmation_status_history_changed_by_user_id'), table_name='bulk_confirmation_status_history')
    op.drop_index(op.f('ix_bulk_confirmation_status_history_created_at'), table_name='bulk_confirmation_status_history')
    op.drop_table('bulk_confirmation_status_history')
    op.drop_index(op.f('ix_bulk_confirmation_activities_activity_type'), table_name='bulk_confirmation_activities')
    op.drop_index(op.f('ix_bulk_confirmation_activities_bulk_confirmation_id'), table_name='bulk_confirmation_activities')
    op.drop_index(op.f('ix_bulk_confirmation_activities_created_at'), table_name='bulk_confirmation_activities')
    op.drop_index(op.f('ix_bulk_confirmation_activities_user_id'), table_name='bulk_confirmation_activities')
    op.drop_table('bulk_confirmation_activities')

    # Drop foreign key constraints from other tables before dropping bulk_certificate_confirmations
    op.drop_constraint(op.f('certificate_confirmation_requ_bulk_certificate_confirmatio_fkey'), 'certificate_confirmation_requests', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_bulk_certificate_confirmation_id'), table_name='invoices')
    op.drop_constraint(op.f('invoices_bulk_certificate_confirmation_id_fkey'), 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_payments_bulk_certificate_confirmation_id'), table_name='payments')
    op.drop_constraint(op.f('payments_bulk_certificate_confirmation_id_fkey'), 'payments', type_='foreignkey')

    # Now we can safely drop bulk_certificate_confirmations table
    op.drop_index(op.f('ix_bulk_certificate_confirmations_assigned_to_user_id'), table_name='bulk_certificate_confirmations')
    op.drop_index(op.f('ix_bulk_certificate_confirmations_bulk_request_number'), table_name='bulk_certificate_confirmations')
    op.drop_index(op.f('ix_bulk_certificate_confirmations_created_at'), table_name='bulk_certificate_confirmations')
    op.drop_index(op.f('ix_bulk_certificate_confirmations_dispatched_by_user_id'), table_name='bulk_certificate_confirmations')
    op.drop_index(op.f('ix_bulk_certificate_confirmations_invoice_id'), table_name='bulk_certificate_confirmations')
    op.drop_index(op.f('ix_bulk_certificate_confirmations_payment_id'), table_name='bulk_certificate_confirmations')
    op.drop_index(op.f('ix_bulk_certificate_confirmations_pdf_generated_by_user_id'), table_name='bulk_certificate_confirmations')
    op.drop_index(op.f('ix_bulk_certificate_confirmations_priority'), table_name='bulk_certificate_confirmations')
    op.drop_index(op.f('ix_bulk_certificate_confirmations_processed_by_user_id'), table_name='bulk_certificate_confirmations')
    op.drop_index(op.f('ix_bulk_certificate_confirmations_request_type'), table_name='bulk_certificate_confirmations')
    op.drop_index(op.f('ix_bulk_certificate_confirmations_service_type'), table_name='bulk_certificate_confirmations')
    op.drop_index(op.f('ix_bulk_certificate_confirmations_status'), table_name='bulk_certificate_confirmations')
    op.drop_table('bulk_certificate_confirmations')
    op.add_column('certificate_confirmation_requests', sa.Column('contact_phone', sa.String(length=50), nullable=False))
    op.add_column('certificate_confirmation_requests', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('certificate_confirmation_requests', sa.Column('certificate_details', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    op.add_column('certificate_confirmation_requests', sa.Column('pdf_file_path', sa.String(length=512), nullable=True))
    op.add_column('certificate_confirmation_requests', sa.Column('pdf_generated_at', sa.DateTime(), nullable=True))
    op.add_column('certificate_confirmation_requests', sa.Column('pdf_generated_by_user_id', sa.UUID(), nullable=True))
    op.add_column('certificate_confirmation_requests', sa.Column('invoice_id', sa.Integer(), nullable=True))
    op.add_column('certificate_confirmation_requests', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.add_column('certificate_confirmation_requests', sa.Column('status', postgresql.ENUM('pending_payment', 'paid', 'in_process', 'ready_for_dispatch', 'dispatched', 'received', 'completed', 'cancelled', name='requeststatus', create_type=False), nullable=False))
    op.add_column('certificate_confirmation_requests', sa.Column('priority', postgresql.ENUM('low', 'medium', 'high', 'urgent', name='ticketpriority', create_type=False), nullable=False))
    op.add_column('certificate_confirmation_requests', sa.Column('service_type', postgresql.ENUM('standard', 'express', name='servicetype', create_type=False), nullable=False))
    op.add_column('certificate_confirmation_requests', sa.Column('assigned_to_user_id', sa.UUID(), nullable=True))
    op.add_column('certificate_confirmation_requests', sa.Column('processed_by_user_id', sa.UUID(), nullable=True))
    op.add_column('certificate_confirmation_requests', sa.Column('dispatched_by_user_id', sa.UUID(), nullable=True))
    op.add_column('certificate_confirmation_requests', sa.Column('dispatched_at', sa.DateTime(), nullable=True))
    op.add_column('certificate_confirmation_requests', sa.Column('tracking_number', sa.String(length=100), nullable=True))
    op.add_column('certificate_confirmation_requests', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('certificate_confirmation_requests', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.add_column('certificate_confirmation_requests', sa.Column('in_process_at', sa.DateTime(), nullable=True))
    op.add_column('certificate_confirmation_requests', sa.Column('ready_for_dispatch_at', sa.DateTime(), nullable=True))
    op.add_column('certificate_confirmation_requests', sa.Column('received_at', sa.DateTime(), nullable=True))
    op.add_column('certificate_confirmation_requests', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # Drop the foreign key constraint index (foreign key constraint already dropped above)
    op.drop_index(op.f('ix_certificate_confirmation_requests_bulk_certificate_c_aed7'), table_name='certificate_confirmation_requests')
    op.drop_index(op.f('ix_certificate_confirmation_requests_candidate_index_number'), table_name='certificate_confirmation_requests')
    op.drop_index(op.f('ix_certificate_confirmation_requests_completion_year'), table_name='certificate_confirmation_requests')
    op.create_index(op.f('ix_certificate_confirmation_requests_assigned_to_user_id'), 'certificate_confirmation_requests', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_certificate_confirmation_requests_created_at'), 'certificate_confirmation_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_certificate_confirmation_requests_dispatched_by_user_id'), 'certificate_confirmation_requests', ['dispatched_by_user_id'], unique=False)
    op.create_index(op.f('ix_certificate_confirmation_requests_invoice_id'), 'certificate_confirmation_requests', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_certificate_confirmation_requests_payment_id'), 'certificate_confirmation_requests', ['payment_id'], unique=False)
    op.create_index(op.f('ix_certificate_confirmation_requests_pdf_generated_by_user_id'), 'certificate_confirmation_requests', ['pdf_generated_by_user_id'], unique=False)
    op.create_index(op.f('ix_certificate_confirmation_requests_priority'), 'certificate_confirmation_requests', ['priority'], unique=False)
    op.create_index(op.f('ix_certificate_confirmation_requests_processed_by_user_id'), 'certificate_confirmation_requests', ['processed_by_user_id'], unique=False)
    op.create_index(op.f('ix_certificate_confirmation_requests_service_type'), 'certificate_confirmation_requests', ['service_type'], unique=False)
    op.create_index(op.f('ix_certificate_confirmation_requests_status'), 'certificate_confirmation_requests', ['status'], unique=False)
    # Foreign key constraint to bulk_certificate_confirmations already dropped above
    op.create_foreign_key(None, 'certificate_confirmation_requests', 'portal_users', ['dispatched_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'certificate_confirmation_requests', 'portal_users', ['pdf_generated_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'certificate_confirmation_requests', 'invoices', ['invoice_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'certificate_confirmation_requests', 'portal_users', ['processed_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'certificate_confirmation_requests', 'portal_users', ['assigned_to_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'certificate_confirmation_requests', 'payments', ['payment_id'], ['id'], ondelete='SET NULL')
    op.drop_column('certificate_confirmation_requests', 'bulk_certificate_confirmation_id')
    op.drop_column('certificate_confirmation_requests', 'candidate_photograph_file_path')
    op.drop_column('certificate_confirmation_requests', 'completion_year')
    op.drop_column('certificate_confirmation_requests', 'candidate_name')
    op.drop_column('certificate_confirmation_requests', 'programme_name')
    op.drop_column('certificate_confirmation_requests', 'candidate_index_number')
    op.drop_column('certificate_confirmation_requests', 'school_name')
    op.drop_column('certificate_confirmation_requests', 'certificate_file_path')
    op.drop_column('certificate_confirmation_requests', 'request_details')
    # Foreign key constraints and indexes already dropped above
    op.drop_column('invoices', 'bulk_certificate_confirmation_id')
    op.drop_column('payments', 'bulk_certificate_confirmation_id')
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    op.add_column('ticket_activities', sa.Column('ticket_type', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_ticket_activities_ticket_type'), 'ticket_activities', ['ticket_type'], unique=False)
    op.drop_constraint(op.f('ticket_activities_ticket_id_fkey'), 'ticket_activities', type_='foreignkey')
    op.add_column('ticket_status_history', sa.Column('ticket_type', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_ticket_status_history_ticket_type'), 'ticket_status_history', ['ticket_type'], unique=False)
    op.drop_constraint(op.f('ticket_status_history_ticket_id_fkey'), 'ticket_status_history', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('ticket_status_history_ticket_id_fkey'), 'ticket_status_history', 'certificate_requests', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_ticket_status_history_ticket_type'), table_name='ticket_status_history')
    op.drop_column('ticket_status_history', 'ticket_type')
    op.create_foreign_key(op.f('ticket_activities_ticket_id_fkey'), 'ticket_activities', 'certificate_requests', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_ticket_activities_ticket_type'), table_name='ticket_activities')
    op.drop_column('ticket_activities', 'ticket_type')
    # op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    # op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.add_column('payments', sa.Column('bulk_certificate_confirmation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('payments_bulk_certificate_confirmation_id_fkey'), 'payments', 'bulk_certificate_confirmations', ['bulk_certificate_confirmation_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_payments_bulk_certificate_confirmation_id'), 'payments', ['bulk_certificate_confirmation_id'], unique=False)
    op.add_column('invoices', sa.Column('bulk_certificate_confirmation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('invoices_bulk_certificate_confirmation_id_fkey'), 'invoices', 'bulk_certificate_confirmations', ['bulk_certificate_confirmation_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_invoices_bulk_certificate_confirmation_id'), 'invoices', ['bulk_certificate_confirmation_id'], unique=True)
    op.add_column('certificate_confirmation_requests', sa.Column('request_details', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('certificate_confirmation_requests', sa.Column('certificate_file_path', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('certificate_confirmation_requests', sa.Column('school_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('certificate_confirmation_requests', sa.Column('candidate_index_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('certificate_confirmation_requests', sa.Column('programme_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('certificate_confirmation_requests', sa.Column('candidate_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('certificate_confirmation_requests', sa.Column('completion_year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('certificate_confirmation_requests', sa.Column('candidate_photograph_file_path', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('certificate_confirmation_requests', sa.Column('bulk_certificate_confirmation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'certificate_confirmation_requests', type_='foreignkey')
    op.drop_constraint(None, 'certificate_confirmation_requests', type_='foreignkey')
    op.drop_constraint(None, 'certificate_confirmation_requests', type_='foreignkey')
    op.drop_constraint(None, 'certificate_confirmation_requests', type_='foreignkey')
    op.drop_constraint(None, 'certificate_confirmation_requests', type_='foreignkey')
    op.drop_constraint(None, 'certificate_confirmation_requests', type_='foreignkey')
    op.create_foreign_key(op.f('certificate_confirmation_requ_bulk_certificate_confirmatio_fkey'), 'certificate_confirmation_requests', 'bulk_certificate_confirmations', ['bulk_certificate_confirmation_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_certificate_confirmation_requests_status'), table_name='certificate_confirmation_requests')
    op.drop_index(op.f('ix_certificate_confirmation_requests_service_type'), table_name='certificate_confirmation_requests')
    op.drop_index(op.f('ix_certificate_confirmation_requests_processed_by_user_id'), table_name='certificate_confirmation_requests')
    op.drop_index(op.f('ix_certificate_confirmation_requests_priority'), table_name='certificate_confirmation_requests')
    op.drop_index(op.f('ix_certificate_confirmation_requests_pdf_generated_by_user_id'), table_name='certificate_confirmation_requests')
    op.drop_index(op.f('ix_certificate_confirmation_requests_payment_id'), table_name='certificate_confirmation_requests')
    op.drop_index(op.f('ix_certificate_confirmation_requests_invoice_id'), table_name='certificate_confirmation_requests')
    op.drop_index(op.f('ix_certificate_confirmation_requests_dispatched_by_user_id'), table_name='certificate_confirmation_requests')
    op.drop_index(op.f('ix_certificate_confirmation_requests_created_at'), table_name='certificate_confirmation_requests')
    op.drop_index(op.f('ix_certificate_confirmation_requests_assigned_to_user_id'), table_name='certificate_confirmation_requests')
    op.create_index(op.f('ix_certificate_confirmation_requests_completion_year'), 'certificate_confirmation_requests', ['completion_year'], unique=False)
    op.create_index(op.f('ix_certificate_confirmation_requests_candidate_index_number'), 'certificate_confirmation_requests', ['candidate_index_number'], unique=False)
    op.create_index(op.f('ix_certificate_confirmation_requests_bulk_certificate_c_aed7'), 'certificate_confirmation_requests', ['bulk_certificate_confirmation_id'], unique=False)
    op.drop_column('certificate_confirmation_requests', 'completed_at')
    op.drop_column('certificate_confirmation_requests', 'received_at')
    op.drop_column('certificate_confirmation_requests', 'ready_for_dispatch_at')
    op.drop_column('certificate_confirmation_requests', 'in_process_at')
    op.drop_column('certificate_confirmation_requests', 'paid_at')
    op.drop_column('certificate_confirmation_requests', 'notes')
    op.drop_column('certificate_confirmation_requests', 'tracking_number')
    op.drop_column('certificate_confirmation_requests', 'dispatched_at')
    op.drop_column('certificate_confirmation_requests', 'dispatched_by_user_id')
    op.drop_column('certificate_confirmation_requests', 'processed_by_user_id')
    op.drop_column('certificate_confirmation_requests', 'assigned_to_user_id')
    op.drop_column('certificate_confirmation_requests', 'service_type')
    op.drop_column('certificate_confirmation_requests', 'priority')
    op.drop_column('certificate_confirmation_requests', 'status')
    op.drop_column('certificate_confirmation_requests', 'payment_id')
    op.drop_column('certificate_confirmation_requests', 'invoice_id')
    op.drop_column('certificate_confirmation_requests', 'pdf_generated_by_user_id')
    op.drop_column('certificate_confirmation_requests', 'pdf_generated_at')
    op.drop_column('certificate_confirmation_requests', 'pdf_file_path')
    op.drop_column('certificate_confirmation_requests', 'certificate_details')
    op.drop_column('certificate_confirmation_requests', 'contact_email')
    op.drop_column('certificate_confirmation_requests', 'contact_phone')
    op.create_table('bulk_confirmation_activities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bulk_confirmation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_type', postgresql.ENUM('comment', 'status_change', 'assignment', 'note', 'system', name='ticketactivitytype', create_type=False), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('old_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('new_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('old_assigned_to', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('new_assigned_to', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bulk_confirmation_id'], ['bulk_certificate_confirmations.id'], name=op.f('bulk_confirmation_activities_bulk_confirmation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['portal_users.id'], name=op.f('bulk_confirmation_activities_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('bulk_confirmation_activities_pkey'))
    )
    op.create_index(op.f('ix_bulk_confirmation_activities_user_id'), 'bulk_confirmation_activities', ['user_id'], unique=False)
    op.create_index(op.f('ix_bulk_confirmation_activities_created_at'), 'bulk_confirmation_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_bulk_confirmation_activities_bulk_confirmation_id'), 'bulk_confirmation_activities', ['bulk_confirmation_id'], unique=False)
    op.create_index(op.f('ix_bulk_confirmation_activities_activity_type'), 'bulk_confirmation_activities', ['activity_type'], unique=False)
    op.create_table('bulk_certificate_confirmations',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('bulk_certificate_confirmations_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('bulk_request_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('request_type', postgresql.ENUM('certificate', 'attestation', 'confirmation', 'verification', name='certificaterequesttype', create_type=False), autoincrement=False, nullable=False),
    sa.Column('contact_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('contact_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('service_type', postgresql.ENUM('standard', 'express', name='servicetype', create_type=False), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending_payment', 'paid', 'in_process', 'ready_for_dispatch', 'dispatched', 'received', 'completed', 'cancelled', name='requeststatus', create_type=False), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('pdf_file_path', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('pdf_generated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('pdf_generated_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assigned_to_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('priority', postgresql.ENUM('low', 'medium', 'high', 'urgent', name='ticketpriority', create_type=False), autoincrement=False, nullable=False),
    sa.Column('processed_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('dispatched_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('dispatched_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('tracking_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('in_process_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ready_for_dispatch_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['portal_users.id'], name='bulk_certificate_confirmations_assigned_to_user_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dispatched_by_user_id'], ['portal_users.id'], name='bulk_certificate_confirmations_dispatched_by_user_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name='bulk_certificate_confirmations_invoice_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name='bulk_certificate_confirmations_payment_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pdf_generated_by_user_id'], ['portal_users.id'], name='bulk_certificate_confirmations_pdf_generated_by_user_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['processed_by_user_id'], ['portal_users.id'], name='bulk_certificate_confirmations_processed_by_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='bulk_certificate_confirmations_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_bulk_certificate_confirmations_status'), 'bulk_certificate_confirmations', ['status'], unique=False)
    op.create_index(op.f('ix_bulk_certificate_confirmations_service_type'), 'bulk_certificate_confirmations', ['service_type'], unique=False)
    op.create_index(op.f('ix_bulk_certificate_confirmations_request_type'), 'bulk_certificate_confirmations', ['request_type'], unique=False)
    op.create_index(op.f('ix_bulk_certificate_confirmations_processed_by_user_id'), 'bulk_certificate_confirmations', ['processed_by_user_id'], unique=False)
    op.create_index(op.f('ix_bulk_certificate_confirmations_priority'), 'bulk_certificate_confirmations', ['priority'], unique=False)
    op.create_index(op.f('ix_bulk_certificate_confirmations_pdf_generated_by_user_id'), 'bulk_certificate_confirmations', ['pdf_generated_by_user_id'], unique=False)
    op.create_index(op.f('ix_bulk_certificate_confirmations_payment_id'), 'bulk_certificate_confirmations', ['payment_id'], unique=False)
    op.create_index(op.f('ix_bulk_certificate_confirmations_invoice_id'), 'bulk_certificate_confirmations', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_bulk_certificate_confirmations_dispatched_by_user_id'), 'bulk_certificate_confirmations', ['dispatched_by_user_id'], unique=False)
    op.create_index(op.f('ix_bulk_certificate_confirmations_created_at'), 'bulk_certificate_confirmations', ['created_at'], unique=False)
    op.create_index(op.f('ix_bulk_certificate_confirmations_bulk_request_number'), 'bulk_certificate_confirmations', ['bulk_request_number'], unique=True)
    op.create_index(op.f('ix_bulk_certificate_confirmations_assigned_to_user_id'), 'bulk_certificate_confirmations', ['assigned_to_user_id'], unique=False)
    op.create_table('bulk_confirmation_status_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bulk_confirmation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('from_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('to_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bulk_confirmation_id'], ['bulk_certificate_confirmations.id'], name=op.f('bulk_confirmation_status_history_bulk_confirmation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['portal_users.id'], name=op.f('bulk_confirmation_status_history_changed_by_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('bulk_confirmation_status_history_pkey'))
    )
    op.create_index(op.f('ix_bulk_confirmation_status_history_created_at'), 'bulk_confirmation_status_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_bulk_confirmation_status_history_changed_by_user_id'), 'bulk_confirmation_status_history', ['changed_by_user_id'], unique=False)
    op.create_index(op.f('ix_bulk_confirmation_status_history_bulk_confirmation_id'), 'bulk_confirmation_status_history', ['bulk_confirmation_id'], unique=False)
    # ### end Alembic commands ###
