"""Drop exmainer application models

Revision ID: a54d56bb1b7c
Revises: 475d1203c946
Create Date: 2026-01-28 13:53:38.161951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a54d56bb1b7c'
down_revision: Union[str, Sequence[str], None] = '475d1203c946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_examiner_work_experiences_application_id'), table_name='examiner_work_experiences')
    op.drop_table('examiner_work_experiences')
    op.drop_index(op.f('ix_examiner_teaching_experiences_application_id'), table_name='examiner_teaching_experiences')
    op.drop_table('examiner_teaching_experiences')
    op.drop_index(op.f('ix_examiner_academic_qualifications_application_id'), table_name='examiner_academic_qualifications')
    op.drop_table('examiner_academic_qualifications')
    op.drop_index(op.f('ix_examiner_training_courses_application_id'), table_name='examiner_training_courses')
    op.drop_table('examiner_training_courses')
    op.drop_index(op.f('ix_examiner_application_documents_application_id'), table_name='examiner_application_documents')
    op.drop_index(op.f('ix_examiner_application_documents_document_type'), table_name='examiner_application_documents')
    op.drop_table('examiner_application_documents')
    op.drop_index(op.f('ix_examiner_application_processing_accepted_officer_user_id'), table_name='examiner_application_processing')
    op.drop_index(op.f('ix_examiner_application_processing_application_id'), table_name='examiner_application_processing')
    op.drop_index(op.f('ix_examiner_application_processing_certificates_checked_f1e4'), table_name='examiner_application_processing')
    op.drop_index(op.f('ix_examiner_application_processing_checked_by_user_id'), table_name='examiner_application_processing')
    op.drop_index(op.f('ix_examiner_application_processing_rejected_officer_user_id'), table_name='examiner_application_processing')
    op.drop_table('examiner_application_processing')
    op.drop_index(op.f('ix_examiner_recommendations_application_id'), table_name='examiner_recommendations')
    op.drop_index(op.f('ix_examiner_recommendations_completed_at'), table_name='examiner_recommendations')
    op.drop_index(op.f('ix_examiner_recommendations_token'), table_name='examiner_recommendations')
    op.drop_index(op.f('ix_examiner_recommendations_token_expires_at'), table_name='examiner_recommendations')
    op.drop_table('examiner_recommendations')
    op.drop_index(op.f('ix_examiner_examining_experiences_application_id'), table_name='examiner_examining_experiences')
    op.drop_table('examiner_examining_experiences')
    op.drop_index(op.f('ix_examiner_application_subject_preferences_application_id'), table_name='examiner_application_subject_preferences')
    op.drop_table('examiner_application_subject_preferences')
    op.drop_index(op.f('ix_examiner_applications_applicant_id'), table_name='examiner_applications')
    op.drop_index(op.f('ix_examiner_applications_application_number'), table_name='examiner_applications')
    op.drop_index(op.f('ix_examiner_applications_created_at'), table_name='examiner_applications')
    op.drop_index(op.f('ix_examiner_applications_invoice_id'), table_name='examiner_applications')
    op.drop_index(op.f('ix_examiner_applications_payment_status'), table_name='examiner_applications')
    op.drop_index(op.f('ix_examiner_applications_status'), table_name='examiner_applications')
    op.drop_index(op.f('ix_examiner_applications_submitted_at'), table_name='examiner_applications')
    op.drop_table('examiner_applications')
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    sa.Enum('PHOTOGRAPH', 'CERTIFICATE', 'TRANSCRIPT', name='examinerdocumenttype').drop(op.get_bind())
    sa.Enum('ELECTIVE', 'CORE', 'TECHNICAL_DRAWING_BUILDING', 'TECHNICAL_DRAWING_MECHANICAL', 'PRACTICAL_COMPONENT', 'ACCESS_COURSE', name='examinersubjectpreferencetype').drop(op.get_bind())
    sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', name='examinerapplicationstatus').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', name='examinerapplicationstatus').create(op.get_bind())
    sa.Enum('ELECTIVE', 'CORE', 'TECHNICAL_DRAWING_BUILDING', 'TECHNICAL_DRAWING_MECHANICAL', 'PRACTICAL_COMPONENT', 'ACCESS_COURSE', name='examinersubjectpreferencetype').create(op.get_bind())
    sa.Enum('PHOTOGRAPH', 'CERTIFICATE', 'TRANSCRIPT', name='examinerdocumenttype').create(op.get_bind())
    # op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    # op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.create_table('examiner_application_subject_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preference_type', postgresql.ENUM('ELECTIVE', 'CORE', 'TECHNICAL_DRAWING_BUILDING', 'TECHNICAL_DRAWING_MECHANICAL', 'PRACTICAL_COMPONENT', 'ACCESS_COURSE', name='examinersubjectpreferencetype', create_type=False), autoincrement=False, nullable=False),
    sa.Column('subject_area', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['examiner_applications.id'], name=op.f('examiner_application_subject_preferences_application_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('examiner_application_subject_preferences_pkey'))
    )
    op.create_index(op.f('ix_examiner_application_subject_preferences_application_id'), 'examiner_application_subject_preferences', ['application_id'], unique=False)
    op.create_table('examiner_examining_experiences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('examination_body', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('level', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('date_from', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('date_to', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['examiner_applications.id'], name=op.f('examiner_examining_experiences_application_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('examiner_examining_experiences_pkey'))
    )
    op.create_index(op.f('ix_examiner_examining_experiences_application_id'), 'examiner_examining_experiences', ['application_id'], unique=False)
    op.create_table('examiner_applications',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('examiner_applications_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('applicant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('application_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', name='examinerapplicationstatus', create_type=False), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('nationality', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('office_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('residential_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('telephone_office', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('telephone_cell', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('present_school_institution', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('present_rank_position', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('subject_area', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('additional_information', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ceased_examining_explanation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payment_status', postgresql.ENUM('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', name='paymentstatus', create_type=False), autoincrement=False, nullable=True),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['portal_users.id'], name='examiner_applications_applicant_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name='examiner_applications_invoice_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='examiner_applications_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_examiner_applications_submitted_at'), 'examiner_applications', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_examiner_applications_status'), 'examiner_applications', ['status'], unique=False)
    op.create_index(op.f('ix_examiner_applications_payment_status'), 'examiner_applications', ['payment_status'], unique=False)
    op.create_index(op.f('ix_examiner_applications_invoice_id'), 'examiner_applications', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_examiner_applications_created_at'), 'examiner_applications', ['created_at'], unique=False)
    op.create_index(op.f('ix_examiner_applications_application_number'), 'examiner_applications', ['application_number'], unique=True)
    op.create_index(op.f('ix_examiner_applications_applicant_id'), 'examiner_applications', ['applicant_id'], unique=False)
    op.create_table('examiner_recommendations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recommender_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('recommender_status', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('recommender_office_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommender_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('quality_ratings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('integrity_assessment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('certification_statement', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommendation_decision', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('recommender_signature', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('recommender_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('token_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['examiner_applications.id'], name=op.f('examiner_recommendations_application_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('examiner_recommendations_pkey'))
    )
    op.create_index(op.f('ix_examiner_recommendations_token_expires_at'), 'examiner_recommendations', ['token_expires_at'], unique=False)
    op.create_index(op.f('ix_examiner_recommendations_token'), 'examiner_recommendations', ['token'], unique=True)
    op.create_index(op.f('ix_examiner_recommendations_completed_at'), 'examiner_recommendations', ['completed_at'], unique=False)
    op.create_index(op.f('ix_examiner_recommendations_application_id'), 'examiner_recommendations', ['application_id'], unique=True)
    op.create_table('examiner_application_processing',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('checked_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('received_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('certificate_types', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('certificates_checked_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('certificates_checked_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('accepted_first_invitation_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('accepted_subject', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('accepted_officer_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('accepted_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('rejected_reasons', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rejected_officer_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('rejected_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['accepted_officer_user_id'], ['portal_users.id'], name=op.f('examiner_application_processing_accepted_officer_user_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['application_id'], ['examiner_applications.id'], name=op.f('examiner_application_processing_application_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['certificates_checked_by_user_id'], ['portal_users.id'], name=op.f('examiner_application_processi_certificates_checked_by_user_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['checked_by_user_id'], ['portal_users.id'], name=op.f('examiner_application_processing_checked_by_user_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rejected_officer_user_id'], ['portal_users.id'], name=op.f('examiner_application_processing_rejected_officer_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('examiner_application_processing_pkey'))
    )
    op.create_index(op.f('ix_examiner_application_processing_rejected_officer_user_id'), 'examiner_application_processing', ['rejected_officer_user_id'], unique=False)
    op.create_index(op.f('ix_examiner_application_processing_checked_by_user_id'), 'examiner_application_processing', ['checked_by_user_id'], unique=False)
    op.create_index(op.f('ix_examiner_application_processing_certificates_checked_f1e4'), 'examiner_application_processing', ['certificates_checked_by_user_id'], unique=False)
    op.create_index(op.f('ix_examiner_application_processing_application_id'), 'examiner_application_processing', ['application_id'], unique=True)
    op.create_index(op.f('ix_examiner_application_processing_accepted_officer_user_id'), 'examiner_application_processing', ['accepted_officer_user_id'], unique=False)
    op.create_table('examiner_application_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_type', postgresql.ENUM('PHOTOGRAPH', 'CERTIFICATE', 'TRANSCRIPT', name='examinerdocumenttype', create_type=False), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['examiner_applications.id'], name=op.f('examiner_application_documents_application_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('examiner_application_documents_pkey'))
    )
    op.create_index(op.f('ix_examiner_application_documents_document_type'), 'examiner_application_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_examiner_application_documents_application_id'), 'examiner_application_documents', ['application_id'], unique=False)
    op.create_table('examiner_training_courses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organizer', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('course_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('place', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('date_from', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('date_to', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('reason_for_participation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['examiner_applications.id'], name=op.f('examiner_training_courses_application_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('examiner_training_courses_pkey'))
    )
    op.create_index(op.f('ix_examiner_training_courses_application_id'), 'examiner_training_courses', ['application_id'], unique=False)
    op.create_table('examiner_academic_qualifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('university_college', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('degree_diploma', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('class_of_degree', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('major_subjects', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_of_award', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['examiner_applications.id'], name=op.f('examiner_academic_qualifications_application_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('examiner_academic_qualifications_pkey'))
    )
    op.create_index(op.f('ix_examiner_academic_qualifications_application_id'), 'examiner_academic_qualifications', ['application_id'], unique=False)
    op.create_table('examiner_teaching_experiences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('institution_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('date_from', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('date_to', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('level', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['examiner_applications.id'], name=op.f('examiner_teaching_experiences_application_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('examiner_teaching_experiences_pkey'))
    )
    op.create_index(op.f('ix_examiner_teaching_experiences_application_id'), 'examiner_teaching_experiences', ['application_id'], unique=False)
    op.create_table('examiner_work_experiences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('occupation', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('employer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('date_from', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('date_to', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('position_held', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['examiner_applications.id'], name=op.f('examiner_work_experiences_application_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('examiner_work_experiences_pkey'))
    )
    op.create_index(op.f('ix_examiner_work_experiences_application_id'), 'examiner_work_experiences', ['application_id'], unique=False)
    # ### end Alembic commands ###
