"""Add response reference number field

Revision ID: aba8625d46a6
Revises: f7g8h9i0j1k2
Create Date: 2026-01-09 14:09:27.993699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aba8625d46a6'
down_revision: Union[str, Sequence[str], None] = 'f7g8h9i0j1k2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate_confirmation_requests', sa.Column('response_reference_number', sa.String(length=50), nullable=True))
    op.drop_index(op.f('ix_certificate_confirmation_requests_response_revoked_by_user_i'), table_name='certificate_confirmation_requests')
    op.create_index(op.f('ix_certificate_confirmation_requests_response_reference_number'), 'certificate_confirmation_requests', ['response_reference_number'], unique=False)
    op.create_index(op.f('ix_certificate_confirmation_requests_response_revoked_by_user_id'), 'certificate_confirmation_requests', ['response_revoked_by_user_id'], unique=False)
    op.create_index(op.f('ix_certificate_confirmation_requests_response_signed'), 'certificate_confirmation_requests', ['response_signed'], unique=False)
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    # op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.drop_index(op.f('ix_certificate_confirmation_requests_response_signed'), table_name='certificate_confirmation_requests')
    op.drop_index(op.f('ix_certificate_confirmation_requests_response_revoked_by_user_id'), table_name='certificate_confirmation_requests')
    op.drop_index(op.f('ix_certificate_confirmation_requests_response_reference_number'), table_name='certificate_confirmation_requests')
    op.create_index(op.f('ix_certificate_confirmation_requests_response_revoked_by_user_i'), 'certificate_confirmation_requests', ['response_revoked_by_user_id'], unique=False)
    op.drop_column('certificate_confirmation_requests', 'response_reference_number')
    # ### end Alembic commands ###
