"""Update grading options

Revision ID: be281c6e6782
Revises: a54d56bb1b7c
Create Date: 2026-01-30 22:51:23.827391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'be281c6e6782'
down_revision: Union[str, Sequence[str], None] = 'a54d56bb1b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    op.sync_enum_values(
        enum_schema='public',
        enum_name='grade',
        new_values=['FAIL', 'PASS', 'LOWER_CREDIT', 'CREDIT', 'UPPER_CREDIT', 'DISTINCTION', 'BLOCKED', 'CANCELLED', 'ABSENT', 'PENDING'],
        affected_columns=[TableReference(table_schema='public', table_name='candidate_results', column_name='grade')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='grade',
        new_values=['FAIL', 'PASS', 'LOWER_CREDIT', 'CREDIT', 'UPPER_CREDIT', 'DISTINCTION', 'BLOCKED', 'CANCELLED', 'ABSENT'],
        affected_columns=[TableReference(table_schema='public', table_name='candidate_results', column_name='grade')],
        enum_values_to_rename=[],
    )
    # op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    # op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    # ### end Alembic commands ###
