"""Initregistration db

Revision ID: d5355974bdcb
Revises:
Create Date: 2026-01-01 16:21:05.785695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5355974bdcb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_registration_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_start_date', sa.DateTime(), nullable=False),
    sa.Column('registration_end_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('allows_bulk_registration', sa.Boolean(), nullable=False),
    sa.Column('allows_private_registration', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_code'), 'schools', ['code'], unique=True)
    op.create_table('portal_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.Enum('SYSTEM_ADMIN', 'SCHOOL_ADMIN', 'SCHOOL_USER', 'PRIVATE_USER', name='portalusertype'), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_users_email'), 'portal_users', ['email'], unique=True)
    op.create_index(op.f('ix_portal_users_school_id'), 'portal_users', ['school_id'], unique=False)
    op.create_table('registration_exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id_main_system', sa.Integer(), nullable=True),
    sa.Column('exam_type', sa.String(length=50), nullable=False),
    sa.Column('exam_series', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('registration_period_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registration_period_id'], ['exam_registration_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_exams_exam_id_main_system'), 'registration_exams', ['exam_id_main_system'], unique=False)
    op.create_index(op.f('ix_registration_exams_registration_period_id'), 'registration_exams', ['registration_period_id'], unique=False)
    op.create_table('examination_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_exam_id', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(length=10), nullable=False),
    sa.Column('subject_name', sa.String(length=255), nullable=False),
    sa.Column('examination_date', sa.Date(), nullable=False),
    sa.Column('examination_time', sa.Time(), nullable=False),
    sa.Column('examination_end_time', sa.Time(), nullable=True),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registration_exam_id'], ['registration_exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_exam_id', 'subject_code', name='uq_exam_subject_schedule')
    )
    op.create_index(op.f('ix_examination_schedules_registration_exam_id'), 'examination_schedules', ['registration_exam_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['portal_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('registration_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_exam_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('portal_user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=False),
    sa.Column('index_number', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('programme_code', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('national_id', sa.String(length=50), nullable=True),
    sa.Column('registration_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='registrationstatus'), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portal_user_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registration_exam_id'], ['registration_exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_candidates_index_number'), 'registration_candidates', ['index_number'], unique=False)
    op.create_index(op.f('ix_registration_candidates_portal_user_id'), 'registration_candidates', ['portal_user_id'], unique=False)
    op.create_index(op.f('ix_registration_candidates_registration_exam_id'), 'registration_candidates', ['registration_exam_id'], unique=False)
    op.create_index(op.f('ix_registration_candidates_registration_number'), 'registration_candidates', ['registration_number'], unique=True)
    op.create_index(op.f('ix_registration_candidates_registration_status'), 'registration_candidates', ['registration_status'], unique=False)
    op.create_index(op.f('ix_registration_candidates_school_id'), 'registration_candidates', ['school_id'], unique=False)
    op.create_table('registration_exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('exported_by_user_id', sa.UUID(), nullable=True),
    sa.Column('export_status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='exportstatus'), nullable=False),
    sa.Column('export_file_path', sa.String(length=512), nullable=True),
    sa.Column('export_format', sa.String(length=10), nullable=False),
    sa.Column('total_registrations', sa.Integer(), nullable=False),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['registration_exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exported_by_user_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_exports_exam_id'), 'registration_exports', ['exam_id'], unique=False)
    op.create_index(op.f('ix_registration_exports_export_status'), 'registration_exports', ['export_status'], unique=False)
    op.create_index(op.f('ix_registration_exports_exported_by_user_id'), 'registration_exports', ['exported_by_user_id'], unique=False)
    op.create_table('registration_subject_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_candidate_id', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(length=10), nullable=False),
    sa.Column('subject_name', sa.String(length=255), nullable=False),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registration_candidate_id'], ['registration_candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_subject_selections_registration_candidate_id'), 'registration_subject_selections', ['registration_candidate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_subject_selections_registration_candidate_id'), table_name='registration_subject_selections')
    op.drop_table('registration_subject_selections')
    op.drop_index(op.f('ix_registration_exports_exported_by_user_id'), table_name='registration_exports')
    op.drop_index(op.f('ix_registration_exports_export_status'), table_name='registration_exports')
    op.drop_index(op.f('ix_registration_exports_exam_id'), table_name='registration_exports')
    op.drop_table('registration_exports')
    op.drop_index(op.f('ix_registration_candidates_school_id'), table_name='registration_candidates')
    op.drop_index(op.f('ix_registration_candidates_registration_status'), table_name='registration_candidates')
    op.drop_index(op.f('ix_registration_candidates_registration_number'), table_name='registration_candidates')
    op.drop_index(op.f('ix_registration_candidates_registration_exam_id'), table_name='registration_candidates')
    op.drop_index(op.f('ix_registration_candidates_portal_user_id'), table_name='registration_candidates')
    op.drop_index(op.f('ix_registration_candidates_index_number'), table_name='registration_candidates')
    op.drop_table('registration_candidates')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_examination_schedules_registration_exam_id'), table_name='examination_schedules')
    op.drop_table('examination_schedules')
    op.drop_index(op.f('ix_registration_exams_registration_period_id'), table_name='registration_exams')
    op.drop_index(op.f('ix_registration_exams_exam_id_main_system'), table_name='registration_exams')
    op.drop_table('registration_exams')
    op.drop_index(op.f('ix_portal_users_school_id'), table_name='portal_users')
    op.drop_index(op.f('ix_portal_users_email'), table_name='portal_users')
    op.drop_table('portal_users')
    op.drop_index(op.f('ix_schools_code'), table_name='schools')
    op.drop_table('schools')
    op.drop_table('exam_registration_periods')
    # ### end Alembic commands ###
