"""Add registration pricing and payment fields

Revision ID: dcad8dd0f290
Revises: ecc45d517eff
Create Date: 2026-01-11 20:44:55.682839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcad8dd0f290'
down_revision: Union[str, Sequence[str], None] = 'ecc45d517eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_application_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['registration_exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_application_fees_exam_id'), 'registration_application_fees', ['exam_id'], unique=True)
    op.create_index(op.f('ix_registration_application_fees_is_active'), 'registration_application_fees', ['is_active'], unique=False)
    op.create_table('registration_tiered_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('min_subjects', sa.Integer(), nullable=False),
    sa.Column('max_subjects', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['registration_exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'min_subjects', 'max_subjects', name='uq_tiered_pricing')
    )
    op.create_index(op.f('ix_registration_tiered_pricing_exam_id'), 'registration_tiered_pricing', ['exam_id'], unique=False)
    op.create_index(op.f('ix_registration_tiered_pricing_is_active'), 'registration_tiered_pricing', ['is_active'], unique=False)
    op.create_table('subject_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['registration_exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'exam_id', name='uq_subject_pricing')
    )
    op.create_index(op.f('ix_subject_pricing_exam_id'), 'subject_pricing', ['exam_id'], unique=False)
    op.create_index(op.f('ix_subject_pricing_is_active'), 'subject_pricing', ['is_active'], unique=False)
    op.create_index(op.f('ix_subject_pricing_subject_id'), 'subject_pricing', ['subject_id'], unique=False)
    op.add_column('invoices', sa.Column('registration_candidate_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_invoices_registration_candidate_id'), 'invoices', ['registration_candidate_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'registration_candidates', ['registration_candidate_id'], ['id'], ondelete='SET NULL')
    op.add_column('payments', sa.Column('registration_candidate_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_payments_registration_candidate_id'), 'payments', ['registration_candidate_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'registration_candidates', ['registration_candidate_id'], ['id'], ondelete='SET NULL')
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # Add total_paid_amount as nullable first, then set default values, then make NOT NULL
    op.add_column('registration_candidates', sa.Column('total_paid_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    # Update existing rows to have 0 as the default value
    op.execute("UPDATE registration_candidates SET total_paid_amount = 0 WHERE total_paid_amount IS NULL")
    # Now make the column NOT NULL
    op.alter_column('registration_candidates', 'total_paid_amount',
                    existing_type=sa.Numeric(precision=10, scale=2),
                    nullable=False,
                    server_default='0')
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    op.drop_column('registration_candidates', 'total_paid_amount')
    # op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_registration_candidate_id'), table_name='payments')
    op.drop_column('payments', 'registration_candidate_id')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_registration_candidate_id'), table_name='invoices')
    op.drop_column('invoices', 'registration_candidate_id')
    op.drop_index(op.f('ix_subject_pricing_subject_id'), table_name='subject_pricing')
    op.drop_index(op.f('ix_subject_pricing_is_active'), table_name='subject_pricing')
    op.drop_index(op.f('ix_subject_pricing_exam_id'), table_name='subject_pricing')
    op.drop_table('subject_pricing')
    op.drop_index(op.f('ix_registration_tiered_pricing_is_active'), table_name='registration_tiered_pricing')
    op.drop_index(op.f('ix_registration_tiered_pricing_exam_id'), table_name='registration_tiered_pricing')
    op.drop_table('registration_tiered_pricing')
    op.drop_index(op.f('ix_registration_application_fees_is_active'), table_name='registration_application_fees')
    op.drop_index(op.f('ix_registration_application_fees_exam_id'), table_name='registration_application_fees')
    op.drop_table('registration_application_fees')
    # ### end Alembic commands ###
