"""Update Auth models

Revision ID: e6cf316340ea
Revises: aba8625d46a6
Create Date: 2026-01-09 15:41:12.636282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6cf316340ea'
down_revision: Union[str, Sequence[str], None] = 'aba8625d46a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('SystemAdmin', 'Director', 'DeputyDirector', 'PrincipalManager', 'SeniorManager', 'Manager', 'Staff', 'SchoolAdmin', 'User', 'PublicUser', name='role').create(op.get_bind())
    op.add_column('portal_users', sa.Column('role', postgresql.ENUM('SystemAdmin', 'Director', 'DeputyDirector', 'PrincipalManager', 'SeniorManager', 'Manager', 'Staff', 'SchoolAdmin', 'User', 'PublicUser', name='role', create_type=False), nullable=False))
    op.drop_column('portal_users', 'user_type')
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    sa.Enum('SYSTEM_ADMIN', 'SCHOOL_ADMIN', 'SCHOOL_USER', 'PRIVATE_USER', 'ADMIN', name='portalusertype').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('SYSTEM_ADMIN', 'SCHOOL_ADMIN', 'SCHOOL_USER', 'PRIVATE_USER', 'ADMIN', name='portalusertype').create(op.get_bind())
    # op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    # op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.add_column('portal_users', sa.Column('user_type', postgresql.ENUM('SYSTEM_ADMIN', 'SCHOOL_ADMIN', 'SCHOOL_USER', 'PRIVATE_USER', 'ADMIN', name='portalusertype', create_type=False), autoincrement=False, nullable=False))
    op.drop_column('portal_users', 'role')
    sa.Enum('SystemAdmin', 'Director', 'DeputyDirector', 'PrincipalManager', 'SeniorManager', 'Manager', 'Staff', 'SchoolAdmin', 'User', 'PublicUser', name='role').drop(op.get_bind())
    # ### end Alembic commands ###
