"""Add RBAC permissions

Revision ID: ecc45d517eff
Revises: 14d00b14a8f4
Create Date: 2026-01-10 15:12:20.407563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecc45d517eff'
down_revision: Union[str, Sequence[str], None] = '14d00b14a8f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', postgresql.ENUM('SystemAdmin', 'Director', 'DeputyDirector', 'PrincipalManager', 'SeniorManager', 'Manager', 'Staff', 'SchoolAdmin', 'SchoolStaff', 'PublicUser', name='role', create_type=False), nullable=False),
    sa.Column('permission_key', sa.String(length=255), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role', 'permission_key', name='uq_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_created_by_user_id'), 'role_permissions', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_permission_key'), 'role_permissions', ['permission_key'], unique=False)
    op.create_index(op.f('ix_role_permissions_role'), 'role_permissions', ['role'], unique=False)
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission_key', sa.String(length=255), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['portal_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'permission_key', name='uq_user_permission')
    )
    op.create_index(op.f('ix_user_permissions_created_by_user_id'), 'user_permissions', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_user_permissions_expires_at'), 'user_permissions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_permissions_permission_key'), 'user_permissions', ['permission_key'], unique=False)
    op.create_index(op.f('ix_user_permissions_user_id'), 'user_permissions', ['user_id'], unique=False)
    # op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    op.sync_enum_values(
        enum_schema='public',
        enum_name='role',
        new_values=['SystemAdmin', 'Director', 'DeputyDirector', 'PrincipalManager', 'SeniorManager', 'Manager', 'Staff', 'SchoolAdmin', 'SchoolStaff', 'PublicUser'],
        affected_columns=[TableReference(table_schema='public', table_name='portal_users', column_name='role'), TableReference(table_schema='public', table_name='role_permissions', column_name='role')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='role',
        new_values=['SystemAdmin', 'Director', 'DeputyDirector', 'PrincipalManager', 'SeniorManager', 'Manager', 'Staff', 'SchoolAdmin', 'User', 'PublicUser'],
        affected_columns=[TableReference(table_schema='public', table_name='portal_users', column_name='role'), TableReference(table_schema='public', table_name='role_permissions', column_name='role')],
        enum_values_to_rename=[],
    )
    # op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    # op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.drop_index(op.f('ix_user_permissions_user_id'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_permission_key'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_expires_at'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_created_by_user_id'), table_name='user_permissions')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_role_permissions_role'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_key'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_created_by_user_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    # ### end Alembic commands ###
