"""Add new fields to candidate model

Revision ID: f06106ce6729
Revises: ffc45d33e80d
Create Date: 2026-01-13 12:16:08.780056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f06106ce6729'
down_revision: Union[str, Sequence[str], None] = 'ffc45d33e80d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('regular', 'private', 'referral', name='registrationtype').create(op.get_bind())
    sa.Enum('Visual', 'Auditory', 'Physical', 'Cognitive', 'Speech', 'Other', name='disability').create(op.get_bind())
    #op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])

    # Add columns as nullable first
    op.add_column('registration_candidates', sa.Column('firstname', sa.String(length=255), nullable=True))
    op.add_column('registration_candidates', sa.Column('lastname', sa.String(length=255), nullable=True))
    op.add_column('registration_candidates', sa.Column('othername', sa.String(length=255), nullable=True))
    op.add_column('registration_candidates', sa.Column('disability', postgresql.ENUM('Visual', 'Auditory', 'Physical', 'Cognitive', 'Speech', 'Other', name='disability', create_type=False), nullable=True))
    op.add_column('registration_candidates', sa.Column('registration_type', postgresql.ENUM('regular', 'private', 'referral', name='registrationtype', create_type=False), nullable=True))
    op.add_column('registration_candidates', sa.Column('guardian_digital_address', sa.String(length=50), nullable=True))
    op.add_column('registration_candidates', sa.Column('guardian_national_id', sa.String(length=50), nullable=True))

    # Migrate existing data: split name into firstname, lastname, othername
    # First word = firstname, second word = lastname, third word (if exists) = othername
    # If name has only 2 words: first = firstname, second = lastname, othername = NULL
    # If name has 3+ words: first = firstname, second = lastname, third = othername (ignore additional words)
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE registration_candidates
        SET
            firstname = (string_to_array(trim(name), ' '))[1],
            lastname = CASE
                WHEN array_length(string_to_array(trim(name), ' '), 1) >= 2
                THEN (string_to_array(trim(name), ' '))[2]
                ELSE (string_to_array(trim(name), ' '))[1]
            END,
            othername = CASE
                WHEN array_length(string_to_array(trim(name), ' '), 1) >= 3
                THEN (string_to_array(trim(name), ' '))[3]
                ELSE NULL
            END
        WHERE name IS NOT NULL AND name != ''
    """))

    # Set default registration_type to 'regular' for existing records
    connection.execute(sa.text("""
        UPDATE registration_candidates
        SET registration_type = 'regular'
        WHERE registration_type IS NULL
    """))

    # Now alter columns to be NOT NULL (only firstname and lastname)
    op.alter_column('registration_candidates', 'firstname', nullable=False)
    op.alter_column('registration_candidates', 'lastname', nullable=False)

    op.create_index(op.f('ix_registration_candidates_registration_type'), 'registration_candidates', ['registration_type'], unique=False)
    op.drop_column('registration_candidates', 'name')
    op.drop_column('registration_candidates', 'guardian_address')
    # op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')

    # Add name column as nullable first
    op.add_column('registration_candidates', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('registration_candidates', sa.Column('guardian_address', sa.TEXT(), autoincrement=False, nullable=True))

    # Reconstruct name from firstname, lastname, othername
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE registration_candidates
        SET name = TRIM(
            CONCAT_WS(' ',
                firstname,
                CASE WHEN othername IS NOT NULL THEN othername ELSE '' END,
                lastname
            )
        )
        WHERE firstname IS NOT NULL AND lastname IS NOT NULL
    """))

    # Now alter name column to be NOT NULL
    op.alter_column('registration_candidates', 'name', nullable=False)

    op.drop_index(op.f('ix_registration_candidates_registration_type'), table_name='registration_candidates')
    op.drop_column('registration_candidates', 'guardian_national_id')
    op.drop_column('registration_candidates', 'guardian_digital_address')
    op.drop_column('registration_candidates', 'registration_type')
    op.drop_column('registration_candidates', 'disability')
    op.drop_column('registration_candidates', 'othername')
    op.drop_column('registration_candidates', 'lastname')
    op.drop_column('registration_candidates', 'firstname')
    #op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    sa.Enum('Visual', 'Auditory', 'Physical', 'Cognitive', 'Speech', 'Other', name='disability').drop(op.get_bind())
    sa.Enum('regular', 'private', 'referral', name='registrationtype').drop(op.get_bind())
    # ### end Alembic commands ###
