"""Add registration_type field to pricing models

Revision ID: ff260e8a59e9
Revises: 796c30db4172
Create Date: 2026-01-13 19:05:25.118607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff260e8a59e9'
down_revision: Union[str, Sequence[str], None] = '796c30db4172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programme_pricing', sa.Column('registration_type', postgresql.ENUM('free_tvet', 'private', 'referral', name='registrationtype', create_type=False), nullable=True))
    op.drop_constraint(op.f('uq_programme_pricing'), 'programme_pricing', type_='unique')
    op.create_unique_constraint('uq_programme_pricing', 'programme_pricing', ['programme_id', 'exam_id', 'registration_type'])
    op.create_index(op.f('ix_programme_pricing_registration_type'), 'programme_pricing', ['registration_type'], unique=False)
    #op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    op.add_column('registration_application_fees', sa.Column('registration_type', postgresql.ENUM('free_tvet', 'private', 'referral', name='registrationtype', create_type=False), nullable=True))
    op.drop_index(op.f('ix_registration_application_fees_exam_id'), table_name='registration_application_fees')
    op.create_index(op.f('ix_registration_application_fees_exam_id'), 'registration_application_fees', ['exam_id'], unique=False)
    op.create_index(op.f('ix_registration_application_fees_registration_type'), 'registration_application_fees', ['registration_type'], unique=False)
    op.create_unique_constraint('uq_application_fee', 'registration_application_fees', ['exam_id', 'registration_type'])
    op.add_column('registration_tiered_pricing', sa.Column('registration_type', postgresql.ENUM('free_tvet', 'private', 'referral', name='registrationtype', create_type=False), nullable=True))
    op.drop_constraint(op.f('uq_tiered_pricing'), 'registration_tiered_pricing', type_='unique')
    op.create_unique_constraint('uq_tiered_pricing', 'registration_tiered_pricing', ['exam_id', 'registration_type', 'min_subjects', 'max_subjects'])
    op.create_index(op.f('ix_registration_tiered_pricing_registration_type'), 'registration_tiered_pricing', ['registration_type'], unique=False)
    #op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    op.add_column('subject_pricing', sa.Column('registration_type', postgresql.ENUM('free_tvet', 'private', 'referral', name='registrationtype', create_type=False), nullable=True))
    op.drop_constraint(op.f('uq_subject_pricing'), 'subject_pricing', type_='unique')
    op.create_unique_constraint('uq_subject_pricing', 'subject_pricing', ['subject_id', 'exam_id', 'registration_type'])
    op.create_index(op.f('ix_subject_pricing_registration_type'), 'subject_pricing', ['registration_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subject_pricing_registration_type'), table_name='subject_pricing')
    op.drop_constraint('uq_subject_pricing', 'subject_pricing', type_='unique')
    op.create_unique_constraint(op.f('uq_subject_pricing'), 'subject_pricing', ['subject_id', 'exam_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('subject_pricing', 'registration_type')
    #op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    op.drop_index(op.f('ix_registration_tiered_pricing_registration_type'), table_name='registration_tiered_pricing')
    op.drop_constraint('uq_tiered_pricing', 'registration_tiered_pricing', type_='unique')
    op.create_unique_constraint(op.f('uq_tiered_pricing'), 'registration_tiered_pricing', ['exam_id', 'min_subjects', 'max_subjects'], postgresql_nulls_not_distinct=False)
    op.drop_column('registration_tiered_pricing', 'registration_type')
    op.drop_constraint('uq_application_fee', 'registration_application_fees', type_='unique')
    op.drop_index(op.f('ix_registration_application_fees_registration_type'), table_name='registration_application_fees')
    op.drop_index(op.f('ix_registration_application_fees_exam_id'), table_name='registration_application_fees')
    op.create_index(op.f('ix_registration_application_fees_exam_id'), 'registration_application_fees', ['exam_id'], unique=True)
    op.drop_column('registration_application_fees', 'registration_type')
    #op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    op.drop_index(op.f('ix_programme_pricing_registration_type'), table_name='programme_pricing')
    op.drop_constraint('uq_programme_pricing', 'programme_pricing', type_='unique')
    op.create_unique_constraint(op.f('uq_programme_pricing'), 'programme_pricing', ['programme_id', 'exam_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('programme_pricing', 'registration_type')
    # ### end Alembic commands ###
