"""Update candidate model

Revision ID: ffc45d33e80d
Revises: 020ec4a481a2
Create Date: 2026-01-12 23:37:01.235456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffc45d33e80d'
down_revision: Union[str, Sequence[str], None] = '020ec4a481a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_unique_constraint('uq_programme_subject', 'programme_subjects', ['programme_id', 'subject_id'])
    op.add_column('registration_candidates', sa.Column('guardian_name', sa.String(length=255), nullable=True))
    op.add_column('registration_candidates', sa.Column('guardian_phone', sa.String(length=50), nullable=True))
    op.add_column('registration_candidates', sa.Column('guardian_address', sa.Text(), nullable=True))
    #op.create_unique_constraint('uq_school_programme', 'school_programmes', ['school_id', 'programme_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint('uq_school_programme', 'school_programmes', type_='unique')
    op.drop_column('registration_candidates', 'guardian_address')
    op.drop_column('registration_candidates', 'guardian_phone')
    op.drop_column('registration_candidates', 'guardian_name')
    #op.drop_constraint('uq_programme_subject', 'programme_subjects', type_='unique')
    # ### end Alembic commands ###
